### ISSUE TITLE
multiple-defined link errors in Windows build due to non-inlined functions in winmath.h

### ISSUE THREAD

**Issue by lefebvrera** [TriBITSPub/TriBITS#116]
The file TriBITS/tribits/win_interface/include/winmath.h has methods that are not inlined, causing multiple-defined link errors.

**Comment by bartlettroscoe** [comment]
I rebased this commit and pushed it.  See [here](https://github.com/TriBITSPub/TriBITS/pull/117#issuecomment-216891532).
