### ISSUE TITLE
Better document how to tenatively enbled TPLs

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#118]
There have been several questions about how to tentatively enable a TPL.  The function `TRIBITS_TPL_TENTATIVELY_ENABLE()` is documented in the TriBITS Developers Guide but it does not state that it should usually be called in a Dependencies.cmake file.  This story is to improve that documentation.

**Comment by bartlettroscoe** [comment]
Because of the urgent need (see below email from Si), I pushed the updated documentation in the commit dfd55a4.  This shows the updated documentation at:

https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-tentatively-enable-a-tpl

Now I would like a post-push review.

@jwillenbring, @bmpersc, or @nmhamster, can one of you please look over this updated documentation?

@nmhamster, since you asked about this, would you be willing to look over this updated documentation?  If you find typos or other problems, please comment on them here.

> -----Original Message-----
> From: Hammond, Simon David (-EXP)
> Sent: Thursday, May 05, 2016 11:28 PM
> To: Bartlett, Roscoe A
> Subject: Tentatively Enabled libdl in Trilinos
> 
> Ross,
> 
> I’m told you’re the guy to speak to. You are probably aware that we have
> profiling hooks now in Kokkos which require dlopen support. We want to
> tentatively enable libdl in the Trilinos configure so we bake these hooks in as
> many installations as is possible. So far users have not seen any performance
> impact of that.
> 
> Can you help me out here, is this something that we can easily do?
> 
> Thanks,
> 
> S.

**Comment by jwillenbring** [comment]
I looked at the documentation and I do not have any suggested changes.

**Comment by bartlettroscoe** [comment]
> I looked at the documentation and I do not have any suggested changes.

@jwillenbring, is it clear how to make a TPL "tentatively enabled" and file to modify to do this in?

**Comment by jwillenbring** [comment]
It seems straight-forward. 

after the 
TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  ...
    )

block in the Dependencies.cmake file, add a 

TRIBITS_TPL_TENTATIVELY_ENABLE(SomeTpl)

entry.

**Comment by bartlettroscoe** [comment]
> It seems straight-forward.
>
> after the
> TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
> ...
> )
>
> block in the Dependencies.cmake file, add a
> 
> TRIBITS_TPL_TENTATIVELY_ENABLE(SomeTpl)
> 
> entry.

That's it!  Thanks Jim!

@nmhamster, let me know if you are the Kokkos developers have any further questions about this.

Review is complete so I am closing.

**Comment by bartlettroscoe** [comment]
Closing for real
