### ISSUE TITLE
TriBITS fails with MinGW

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#129]
I receive the following configuration error using TriBITS.
Windows 10, CMake3.6r1 with MinGW64-4.8.5 toolchain.

```
CMake Error: Error in cmake code at
C:/Users/bogus/projects/tutela/TriBITS/Version.cmake:1:
Parse error.  Expected a command name, got unquoted argument with text "tribits/Version.cmake".
CMake Error at TriBITS/tribits/core/package_arch/TribitsGlobalMacros.cmake:1975 (INCLUDE):
  include could not find load file:

    C:/Users/bogus/projects/tutela/TriBITS/Version.cmake
Call Stack (most recent call first):
  TriBITS/tribits/core/package_arch/TribitsGlobalMacros.cmake:2009 (TRIBITS_REPOSITORY_CONFIGURE_VERSION_HEADER_FILE)
  TriBITS/tribits/core/package_arch/TribitsProjectImpl.cmake:253 (TRIBITS_REPOSITORY_CONFIGURE_ALL_VERSION_HEADER_FILES)
  TriBITS/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:85 (TRIBITS_PROJECT)
```

**Comment by bartlettroscoe** [comment]
@lefebvre,

I will be testing the CMake 3.6 branch soon and I will see if this comes up.

Otherwise, if you can provide a PR that addresses the issue, then that would be great!

**Comment by bartlettroscoe** [comment]
Just curious, but what projects are you using TriBITS with these days?

**Comment by lefebvre** [comment]
@bartlettroscoe I updated to using CMake 3.4.3 and I received the same error.

**Comment by lefebvre** [comment]
@bartlettroscoe  I have two projects that I am using TriBITS in.
I find declaring extra repos as NOPACKAGES so I can rename them as I wish in my directory structure is convenient. Is there anything I loose by doing this?

**Comment by bartlettroscoe** [comment]
> I updated to using CMake 3.4.3 and I received the same error.

Looking at the code, I see this is set as:

```
SET(REPOSITORY_VERSION_FILE ${REPOSITORY_ABS_DIR}/Version.cmake)
```

I am wondering if you are getting bit by #43?  Do you have a TriBITS Repo and Package with the same name but different source dirs (which is currently not allowed but will be fixed as part of #43)?

Can you push your code so some branches somewhere so that I can take a look?  If this is EC, then perhaps you can give me access on the ORNL network.

**Comment by bartlettroscoe** [comment]
> I have two projects that I am using TriBITS in.

Not SCALE, right?  Are you using git or Hg?  I would be interested to hear how that is going.

> I find declaring extra repos as NOPACKAGES so I can rename them as I wish in my directory structure is convenient. Is there anything I loose by doing this?

That works and can make sense in many cases.  This is less overhead because you don't have to supply a PackagesList.cmake or TPLsList.cmake file in these NOPACKAGES VC repos.  You just add the packages list and TPLs list directly the the parent TriBITS repo's files.  But I would need to see the full context and reuse use cases, etc.

Note that once I can complete #43, you can name TriBITS repos anything you want and put them anywhere you want (under the base project repo).

**Comment by lefebvre** [comment]
I have been bitten by #43 before. I haven't introduced any packages since resolving conflicts in the past.

This quick patch, formal include command with include guard, resolves the issue:
```
$ git diff
diff --git a/Version.cmake b/Version.cmake
index 9d915d5..ae13ff7 120000
--- a/Version.cmake
+++ b/Version.cmake
@@ -1 +1,6 @@
-tribits/Version.cmake
\ No newline at end of file
+IF(NOT TRIBITS_VERSION_CMAKE_INCLUDE)
+   SET(TRIBITS_VERSION_CMAKE_INCLUDE TRUE)
+ELSE()
+   RETURN()
+ENDIF()
+INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/tribits/Version.cmake)
```

**Comment by bartlettroscoe** [comment]
> This quick patch, formal include command with include guard, resolves the issue

What, what file is this?   Is the the file:

    TriBITS/tribits/Version.cmake

that is symlinked as

   TriBITS/Version.cmake

?

I think this must be due to a symlink issue or something strange with CMake or the file system on MinGW64.

**Comment by lefebvre** [comment]
So on Linux Version.cmake is a symlink to tribits/Version.cmake.
Symlinks don't work on Windows. 
This indicated that I am including TriBITS differently than other Windows projects (SCALE).
However, both projects simply include TriBITS/tribits/TriBITS.cmake.
I don't know how SCALE is not running into this same issue.

**Comment by bartlettroscoe** [comment]
@lefebvre,

Can you please commit this fix including `#129` in the commit log on a branch and then do a PR to this repo?  That makes all of this easier for me and it removes all ambiguity.  Much easier that raw patches.  And then you get credit once I merge (or rebase) your branch/commits.  See details at [Contributing to TriBITS](https://github.com/TriBITSPub/TriBITS/wiki/Contributing-to-TriBITS#preferred-process-for-suggesting-and-making-changes-to-tribits).

Thanks,

-Ross

**Comment by lefebvre** [comment]
My previous solution fixes the config error, however cmake "stops working".
I found an easier solution.
The problem originated with me listing TriBITS as an extra repo.
I did this so it would receive updates during CI.
The solution was to remove TriBITS from extra repo listing.

**Comment by bartlettroscoe** [comment]
> The solution was to remove TriBITS from extra repo listing.

@lefebvre, where you listing TriBITS as an extra repo in the ExtraRepositoriesList.cmake file?  If you were doing that for the git clones and updates then you can just add NOPACKAGES and it will not try to add TriBITS as a TriBITS repo.  Unless you are developing on TriBITS, there is no reason to add TriBITS as a package.  I stopped doing that a long time ago in Trilinos.

As for the issue of TriBITS/Version.cmake, I am going to move to a model where I configure Version.cmake from Version.cmake.in so I can determine the version automatically from the git tag.  See a discussion of this [here](https://docs.google.com/document/d/1uVQYI2cmNx09fDkHDA136yqDTqayhxqfvjFiuUue7wo/edit#bookmark=id.7cru8wb8ed7).  Therefore, there will not even be a symlink in the future.

**Comment by lefebvre** [comment]
@bartlettroscoe I am encountering this issue again.
I require TriBITS to be an extra repository, but this symlink is causing a configuration error.
I have NOPACKAGES set for TriBITS, but it still presents with this error
```
C:/regression/tutela_nightly/source/TriBITS/Version.cmake:1:
Parse error.  Expected a command name, got unquoted argument with text "tribits/Version.cmake".
CMake Error at C:/regression/tutela_nightly/local/TriBITS/tribits/core/package_arch/TribitsGlobalMacros.cmake:2039 (INCLUDE):
  include could not find load file:

    C:/regression/tutela_nightly/source/TriBITS/Version.cmake
```

So this symlink is switch out for a file with a single line containing the relative path to the link destination.
Any other ideas about how to resolve this issue?

Thanks,
Jordan

**Comment by bartlettroscoe** [comment]
For now I can just duplicate this file and I will put in a configure-time check to make sure they are the same in case I forgot if I change one without updating the other.  Longer term, I want to configure the Version.cmake file taking advantage of the current  git tag.  See:

* https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#bookmark=id.c9fdw29elloo

If I create a branch can you pull it and test it out?

**Comment by lefebvre** [comment]
@bartlettroscoe  no need to make a branch.
I will make a local change and test.

**Comment by lefebvre** [comment]
Yes. This resolves the issue.

**Comment by bartlettroscoe** [comment]
@lefebvre,

I just pushed the commit:

```
commit 164914e2e38a58850ba6a1ec87ca7f3d74d13f3e
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Mon Nov 14 19:15:50 2016 -0700

    Make base Version.cmake file copy for Windows (#129)
    
    You can't use a symlink for this file or it breaks the Windows build of a
    TriBITS project (see #129).
    
    I tested this manually a few different ways and it aborts the configure if it
    detects that these two files are different.  Later, the Version.cmake file
    will be configured so this will not be an issue.
    
    Build/Test Cases Summary
    Enabled Packages:
    Enabled all Packages
    0) MPI_DEBUG => passed: passed=222,notpassed=0 (0.35 min)
    1) SERIAL_RELEASE => passed: passed=222,notpassed=0 (0.31 min)
```

to the TriBITS GitHub 'master' branch.

Can you please try this out to make sure this fixes your problem and then add a comment here?  I will keep this issue in review until I hear back from you.

**Comment by bartlettroscoe** [comment]
Given the comment [above](https://github.com/TriBITSPub/TriBITS/issues/129#issuecomment-260017402), I am going to assume that creating a copy of the Version.cmake file fixes the problem.
