### ISSUE TITLE
Add new developers guide section "How to check for and tweak ‘ENABLE’ variables"

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#142]
This story is to add a new "How To" section to the TriBITS Developers Guide that explains to TriBITS project developers how to check and tweak TriBITS "ENABLE" variables (e.g. package, TPL, etc.).  It can be confusing if you don't realize that TriBITS allows these to be empty or true or false and sets up persistent cache vars that default to empty "".

**Comment by bartlettroscoe** [comment]
An MPACT developer was asking about this so I will try to document this and get his feedback.

**Comment by bartlettroscoe** [comment]
I added the section:

   https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-check-for-and-tweak-tribits-enable-cache-variables

I will now ask the MPACT developer to review.

**Comment by bscollin** [comment]
Just a few minor comments.  

*  Do you define <XXX> and <YYY>?  If its normal notation in the rest of the document, then I’m okay with it.
*  Should e SE packages and TPLs

Other than that, it looks pretty good.

**Comment by bartlettroscoe** [comment]
> Do you define `<XXX> and <YYY>`?  

@bscollin, can you please take a quick look at the first paragraph at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-check-for-and-tweak-tribits-enable-cache-variables

and see if it addresses the issue?

Thanks again for the review!

**Comment by bscollin** [comment]
Yes, this update addresses my issues.

**Comment by bartlettroscoe** [comment]
Thanks.  Closing as complete.

**Comment by bartlettroscoe** [comment]
I made one more update to this section in commit f88cc6e.  Hopefully this will allow those who just want the steps without the explanation to get what they need faster.
