### ISSUE TITLE
Remove usage of eg from checkin-test.py and get working with all recent git versions

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#15]
When the `checkin-test.py` script was first changed to use git from CVS back in 2009, `git` was not very user friendly and we were using a tool called `eg` to make it a little easier to use.  The `checkin-test.py` script was made to use `eg` so it could model correct `eg` usage.  Since that time, `git` has become easier to use and now with git 2.0, it has changed some of the bad default behaviors (e.g. like `git push` pushing all matching branches).  Also, the version of `eg` we are currently using with `checkin-test.py` does not work with newer git versions and creates an extra dependency we have to deal with.

This story ticket is to remove the dependence of `checkin-test.py` on `eg` and instead to use raw `git`. Also, we want to use raw git commits that will work with many different git versions so that we only need to check for a minimum git version (and an old version at that).

By being more explicit about pulling and pushing to specific branches and using the `--porcelain` argument to many commands, it should be pretty easy to make this change and make it work with many different git versions.

As part of this story, I would also like to make the checkin-test.py script work with tracking branches for each repo independently and not assuming 'origin'.  Therefore, pulls would be explicit with:

    git pull <remote> <remotebranch>

where `<remote>` and `<remotebranch>` is specific for each git repo and pushes would be explicit with:

    git push <remote> <localbranch>:<remotebranch>

again where `<remote>` `<localbranch>:<remotebranch>` and specific to each git repo.  The latter would be needed to avoid the issue of raw `git push` pushing all matching branches which is supper dangerous and surprising to most people.

After this story is complete, I am going to change my personal usage to git 2.x and stop using `eg` all together.  Also, I will change the name of `egdist` to `gitdist` and make `gitdist` only look for `git` and not `eg`.

**Comment by bartlettroscoe** [comment]
This is more urgent now that Trilinos developers need to use git > 1.7.1 to avoid an SSH usage bug.

**Comment by bartlettroscoe** [comment]
@mhoemmen, I just pushed an update to the checkin-test.py script to the TriBITS and Trilinos master branches that removes the dependency on eg and now uses raw git.  I added git 2.1.0 to my path and used it to run the checkin-test.py script to push the changes to the TriBITS and Trilinos repos so it seems to work with newer versions of git.  Please pull the updated Trilinos version where you should see the commits:

```
2d2ccd1 "Merge branch 'tribits_github_snapshot'"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Wed Nov 25 19:06:37 2015 -0500 (2 minutes ago)

7d64863 "Automatic snapshot commit from tribits at 1cc1d03"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Wed Nov 25 19:06:23 2015 -0500 (6 minutes ago)

M       cmake/tribits/README.DIRECTORY_CONTENTS.rst
M       cmake/tribits/ci_support/CheckinTest.py
M       cmake/tribits/ci_support/checkin-test.py
M       cmake/tribits/ci_support/clone_extra_repos.py
D       cmake/tribits/ci_support/eg
M       cmake/tribits/ci_support/get-tribits-packages-from-files-list.py
M       cmake/tribits/core/package_arch/TribitsFindPythonInterp.cmake
M       cmake/tribits/ctest_driver/README
M       cmake/tribits/devtools_install/install_devtools.py
M       cmake/tribits/python_utils/GeneralScriptSupport.py
M       cmake/tribits/python_utils/SnapshotDir.py
M       cmake/tribits/python_utils/extract_rst_cmake_doc.py
T       cmake/tribits/python_utils/gitdist
T       cmake/tribits/python_utils/gitdist.py
M       cmake/tribits/python_utils/mockprogram.py
```

Please let me know if this works or not with an updated git version.

This should resolve #97.

I am not going to close this story yet since I also want to require tracking branches and will pull and push to tracking branches.  That will make usage so much easier and will allow me to name my remote anything I want and not 'origin' (which is terrible name if you work with several remotes).

**Comment by mhoemmen** [comment]
Thanks Ross!  I did notice the change (e.g., the `--no-eg-git-version-check` option is no longer accepted) but haven't had a chance to try with git 2.1.x yet (check-in test script for some Tpetra changes is running now).  I really appreciate you working on this and prioritizing it!  It will help SEMS' efforts to standardize Trilinos testing, and also smooth the Github transition.

**Comment by mhoemmen** [comment]
Hm, I'm still having a bit of trouble pushing using the check-in test script.  Is the CHECKIN directory allowed to be outside the source directory?

**Comment by mhoemmen** [comment]
I think it is, but the final pull is still failing for me.  Here's what the check-in test script reports:

7.a.0) Git Repo: ''

Pulling in updates from 'origin' ...

Running: git pull && git rebase --against origin/master

  Running in working directory: /scratch/prj/Trilinos/Trilinos ...

  Writing console output to file /scratch/prj/Trilinos/CHECKIN/pullFinal.out ...

  Runtime for command = 0.023451 minutes

  ==> '': Pull failed!

Final update failed!

**Comment by bartlettroscoe** [comment]
@mhoemmen, can you please attach the generated "pullFinal.out" file?

**Comment by mhoemmen** [comment]
Hold on, I'm trying to get my latest changes (relating to Tpetra performance) through tests first.  Will post as soon as they pass everything :-)

**Comment by mhoemmen** [comment]
From github.com:trilinos/Trilinos
   3055c3a..11f4e50  master     -> origin/master
Auto-merging packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Merge made by the 'recursive' strategy.
 packages/kokkos/config/nvcc_wrapper                | 15 +++-
 packages/kokkos/config/test_all_sandia             | 26 +++---
 packages/kokkos/core/src/KokkosExp_View.hpp        | 12 ++-
 .../kokkos/core/src/OpenMP/Kokkos_OpenMPexec.cpp   |  7 ++
 packages/kokkos/core/unit_test/TestOpenMP.cpp      |  2 +-
 packages/kokkos/core/unit_test/TestSerial.cpp      |  2 +-
 packages/kokkos/core/unit_test/TestThreads.cpp     |  2 +-
 packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp  |  2 +-
 .../tpetra/core/src/Tpetra_MultiVector_def.hpp     | 25 +++---
 .../test/MultiVector/MultiVector_UnitTests.cpp     | 12 +--
 packages/tpetra/kernels/perf_test/blas1.cpp        |  4 +-
 packages/tpetra/kernels/src/Kokkos_Blas1.hpp       | 20 ++---
 packages/tpetra/kernels/src/Kokkos_Blas1_MV.hpp    | 90 +++++++-------------
 packages/tpetra/kernels/src/Kokkos_MV.hpp          |  2 +-
 packages/tpetra/kernels/src/Kokkos_Sparse.hpp      | 10 +--
 packages/tpetra/kernels/src/Kokkos_Sparse_MV.hpp   | 24 ++----
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_abs.hpp  | 18 ++--
 .../src/impl/Kokkos_Blas1_MV_impl_axpby.hpp        | 48 ++++-------
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_dot.hpp  | 54 ++++--------
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_fill.cpp |  8 +-
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_fill.hpp |  9 +-
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_mult.hpp | 27 ++----
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_nrm1.hpp | 18 ++--
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_nrm2.hpp | 18 ++--
 .../src/impl/Kokkos_Blas1_MV_impl_nrm2w.hpp        | 18 ++--
 .../src/impl/Kokkos_Blas1_MV_impl_nrmInf.hpp       | 18 ++--
 .../src/impl/Kokkos_Blas1_MV_impl_recip.hpp        | 18 ++--
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_scal.hpp | 69 +++++----------
 .../kernels/src/impl/Kokkos_Blas1_MV_impl_sum.hpp  | 18 ++--
 .../src/impl/Kokkos_Blas1_MV_impl_update.hpp       | 54 ++++--------
 .../tpetra/kernels/src/impl/Kokkos_Blas1_impl.hpp  | 44 ++++------
 .../src/impl/Kokkos_Sparse_V_impl_spmv_OpenMP.cpp  | 10 +--
 .../kernels/src/impl/Kokkos_Sparse_impl_spmv.hpp   | 98 ++++++++--------------
 33 files changed, 296 insertions(+), 506 deletions(-)
error: unknown option `against'
usage: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] [<upstream>] [<branch>]
   or: git rebase [-i] [options] [--exec <cmd>] [--onto <newbase>] --root [<branch>]
   or: git-rebase --continue | --abort | --skip | --edit-todo

Available options are
    -v, --verbose         display a diffstat of what changed upstream
    -q, --quiet           be quiet. implies --no-stat
    --autostash           automatically stash/stash pop before and after
    --fork-point          use 'merge-base --fork-point' to refine upstream
    --onto ...            rebase onto given branch instead of upstream
    -p, --preserve-merges
                          try to recreate merges instead of ignoring them
    -s, --strategy ...    use the given merge strategy
    --no-ff               cherry-pick all commits, even if unchanged
    -m, --merge           use merging strategies to rebase
    -i, --interactive     let the user edit the list of commits to rebase
    -x, --exec ...        add exec lines after each commit of the editable list
    -k, --keep-empty         preserve empty commits during rebase
    -f, --force-rebase    force rebase even if branch is up to date
    -X, --strategy-option ...
                          pass the argument through to the merge strategy
    --stat                display a diffstat of what changed upstream
    -n, --no-stat         do not show diffstat of what changed upstream
    --verify              allow pre-rebase hook to run
    --rerere-autoupdate   allow rerere to update index with resolved conflicts
    --root                rebase all reachable commits up to the root(s)
    --autosquash          move commits that begin with squash!/fixup! under -i
    --committer-date-is-author-date
                          passed to 'git am'
    --ignore-date         passed to 'git am'
    --whitespace ...      passed to 'git apply'
    --ignore-whitespace   passed to 'git apply'
    -C ...                passed to 'git apply'
    -S, --gpg-sign[=...]  GPG-sign commits

Actions:
    --continue            continue
    --abort               abort and check out the original branch
    --skip                skip current patch and continue
    --edit-todo           edit the todo list during an interactive rebase

**Comment by mhoemmen** [comment]
That above was the contents of pullFinal.out.  Here's the interesting bit:

error: unknown option `against'
usage: git rebase [-i] [options] [--exec ] [--onto ] [] []
or: git rebase [-i] [options] [--exec ] [--onto ] --root []
or: git-rebase --continue | --abort | --skip | --edit-todo

Available options are ...

**Comment by mhoemmen** [comment]
```
$ git version
git version 2.1.3
```

**Comment by mhoemmen** [comment]
(btw in case it wasn't clear, the check-in test script didn't work because the final pull didn't succeed.)

**Comment by bartlettroscoe** [comment]
The argument `--against` is an `eg` argument and is not understood by raw `git`.  My validation pushes did not do a `--rebase` so this command did not get validated.  I will make sure and do a `--rebase` push to make sure.  Pushing in a minute here.

**Comment by bartlettroscoe** [comment]
@mhoemmen, the following two commits were pushed to the Trilinos 'master' branch which should resolve the push issue:

```
2bfc936 "Merge branch 'tribits_github_snapshot'"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Sun Nov 29 10:08:47 2015 -0500 (3 minutes ago)

bb38fda "Automatic snapshot commit from tribits at 92b58be"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Sun Nov 29 10:08:25 2015 -0500 (7 minutes ago)

M       cmake/tribits/ci_support/CheckinTest.py
```

I pushed to the TriBITS github/master branch using `--rebase` so this updated command (without `--against`) has been validated.

Let me know if you have any more problems with this.

NOTE: I still need to get the checkin-test.py script to work with tracking branches and that is what I will do on Monday (along with a few other checkin-test.py updates).

**Comment by mhoemmen** [comment]
I'll try it out as soon as I get the chance -- thanks!

**Comment by mhoemmen** [comment]
@kddevin I'm adding Karen Devine to the CC list, since she reported the original "missing pull*.out files" issue.  Ross' changes fixed that; I was able to get a pullFinal.out file that made clear what was going on.

**Comment by mhoemmen** [comment]
Works for me now!  I was able to use the check-in test script to push. I haven't yet exercised the case where git actually needed to do a rebase, but otherwise everything was fine.  Thanks Ross!!! :-D

**Comment by bartlettroscoe** [comment]
@mhoemmen, if you look in the checkin-test.out log file, it should show you if it did a "git rebase".  Just do:

```
$ git "git rebase" checkin-test.out
```
Does it show that line?

**Comment by mhoemmen** [comment]
It didn't have to do a rebase in this case, because I have the habit of rebasing manually to avoid merge commits.  The only place the word "rebase" occurs in the file is in the printout of the list of arguments to the check-in test script.

Anyway, don't worry, I'm sure it works :-)  If you're worried, I can try making a trivial Tpetra change tomorrow without doing a manual rebase first, so that I get a merge commit.

**Comment by bartlettroscoe** [comment]
The checkin-test.py script rebases by default so it will do so if you pass in `--no-rebase`, it will do a rebase.

**Comment by bartlettroscoe** [comment]
| The checkin-test.py script rebases by default so it will do so if you pass in --no-rebase, it will do a rebase.

That is, __unless__ you pass in `--no-rebase`.

**Comment by bartlettroscoe** [comment]
I pushed an major refactoring to the checkin-test.py script to change it to
use tracking branches (detailed notes are below).  I pushed the individual WIP commits to a the branch
bartlettroscoe/tracking-branches-15.  I did a `git rebase -i @{u}` to squash
all of the individual commits specific to the checkin-test.py script and
pushed to the github/master branch.

This was a *lot* of work (about 20 hours I would guess to push these latest commits).  This is a very difficult script to test by its very nature and the very detailed testing approach to make the test suite run fast.

Next I will update the version in Trilinos and CASL.

----

**Detailed Notes:**

I am going to go ahead and take this on.

1) Replace 'eg' with raw 'git' and update all automated tests:

* Replace 'eg' with 'git' [Done]
* Remove version check for eg/git [Done]

[Done]

2) Replace raw 'git status' with gitdist code that gets the tracking branch and update everything.

All of the repos need tracking branches when:
* --pull or --push is requested (since there needs to be a tracking branch to do those)
* --enable-packages is not passed in and --enable-all-packages is not set to 'on' (since we need to know the tracking branch so that we need to see if there are changed files w.r.t. the tracking branch)

Otherwise, there is no need to run any git commands at all.

ToDo:

* Replace section '2) Commit changes before pulling updates to merge in (NO LONGER SUPPORTED' with section '2) Get and repo statics' and get repo stats [Done]

* Replace 'origin/<currentbranch>' with gitRepoStats.trackingBranch [Done]

* Remove step '0) Get the current branch name' and get rid of inOptions.currentBranch [Done]

* Replace greps of 'git status' with data from repo stats object and update all the tests corectly [Done]

* Print 'git status' only when a status check fails [Done]

* Print out formatted repo status table from gitdist tools [Done]

* Add new function assertRepoHasBranchAndTrackingBranch() and call when needed (see above criteria) and add tests for various use cases [Done]

* Replace usage of getLocalCommitsSummariesStr() with num local commits in repo stats object:
  - Repace getLocalCommitsSummariesStr() with numCommitsInt() [Done]
  - Stop calling getLocalCommitsSummariesStr() when numCommitsInt() == 0
    and remove argument localCommitsExist [Done]

* Add grep for "REQUESTED ACTIONS: PASSED" and "REQUESTED ACTIONS: FAILED" and fix all tests [Done]

* Add output for getLocalCommitsSummariesStr() to all summary emails [Done]

* Skip 'git diff' for repos that have no commits:
  - Skip when gitDiffsWrtTrackingBranchAreNeeded==True and update
    all tests [Done]
  - Skip when numCommitsInt()==0 and update tests [Done]

* Test with --local-do-all --enable-packages=<something> --enable-all-packages=on/off and make sure that no tracking branches are required and no git diffs are performed ...

* Change from "update" to "pull".  This is git, not cvs/svn [Done]

* Add test to make sure push happens if there are is no diff w.r.t. tracking branch but there are commits (rare case but has happened a few times) [Done]

* Grep for all "TriBITS #15" in the code and tests and make sure everything is handled [Done]

* Update documenation [Done]

* Clean up commits 'git rebase -i @{u}' and write good commit message [Done]

* Push individual commits to branch tracking-branches-15 in my github repo [Done]

* Update release notes [Done]

* Push commits to TriBITS github repo (using update checkin-test.py script) [Done]

**Comment by bartlettroscoe** [comment]
I found a few more issues with the checkin-test.py script (one that was existing).  I pushed the updated version of TriBITS to github, Trilinos github and CASL casl-dev master banches.

I am now closing this as complete.

In total, I would guess this cost about 25 hours of my time.

SIDE NOTE: This is a complex script that is hard to keep the automated testing up to date.   I could do more targeted unit testing but it may not help all that much given the current design of the script and the nature of what it does.  It creates directories and files, run a bunch of git commands and has to interpret and process a lot of output.  All things considered, this is pretty good testing and I can run all of the unit tests in less than 30 sec.  If you were using real git repos and commands, it would take much longer and that would be hard to maintain as well.

I am going to close this as complete.

----

**Detailed Notes:**

* Move the listing of local commits after the ammending of commits but before the push! [Done]

* Change to explicit push of <currentbranch> to <trackingbranch> [Done]

* Fix list of extra commit SHA1s to be correct when top commit is a merge commit:
  - Allow for multi-line 'IT' commands [Done]
  - Fix 'git log --pretty=%h ...' command to select all local commits and then
    pop off the top commit. [Done]

* Push updated commits to TriBITS github repo [Done]

* Snapshot updated checkin-test.py script to Trilinos and push [Done]

* Change name of remote 'origin' to 'casl-dev' on VERA repos [Done]

* Merge to VERA casl-dev repo and install updated gitdist script [Done]
