### ISSUE TITLE
Incorrect configuration search paths set in `checkin-test.getConfigurationSearchPaths`

### ISSUE THREAD

**Issue by tjfulle** [TriBITSPub/TriBITS#159]
This issue originated from Trilinos [Issue 482](https://github.com/trilinos/Trilinos/issues/482):

Function `getConfigurationSearchPaths` in `checkin-test.py` has the following incorrectly sets configuration file search paths.  The function contains the following:

```py
  # Always look for the configuration file assuming the checkin-test.py script
  # is run out of the standard snapshotted tribits directory
  # <project-root>/cmake/tribits/.
  result.append(os.path.join(thisFileRealAbsBasePath, '..', '..'))
```

But, `checkin-test.py` actually lives in `<project-root>/cmake/tribits/ci_support`, so it should be

```py
  result.append(os.path.join(thisFileRealAbsBasePath, '..', '..', '..'))
```

This doesn't usually cause a problem, since the function also appends the absolute directory of `checkin-test.py`, which is usually a symlink in the `<project-root>` directory.  But, if `checkin-test.py` is symlinked elsewhere (say, in a build directory), it fails to find the configuration file.

Courses of action are:

1. Create an automated test that exposes the problem and the desired behavior
2. Fix the code to make the test pass

I can look in to a fix Fri. 12/2.

**Comment by bartlettroscoe** [comment]
@tjfulle, thanks for creating this.  I can help you get set up to add some unit tests for these use cases.  The unit test suite for checkin-test.py is very strong but it takes a bit to get into adding to it.  We can discuss that.  Hopefully it will not be too bad.  The good news is that we just need to ensure that the expected configuration file is correctly read and then we can abort the script.

**Comment by tjfulle** [comment]
@bartlettroscoe, I've made the change and run the tests (they all pass except for the test described in #161).  I'll need a little guidance to actually testing the change.  It will require symlinking `checkin-test.py` to some directory and then running tests from there.

**Comment by bartlettroscoe** [comment]
@tjfulle, can you please push what you have to a branch (call it `config-file-search-path-159`) in your GitHub TriBITS fork and then make a PR against this repo's master branch (and check the box about allowing maintainers to add commits)?  That way we can collaborate on this really fast on this branch to work this out.

Can you specify ins specific terms the exact uses case you want to support (exact directory paths and file names, etc.)?

**Comment by tjfulle** [comment]
@bartlettroscoe Done.

A test case would be to symbolically link `checkin-test.py` *anywhere* outside of TriBITS.  Then, `getConfigurationSearchPaths` would have to use the realpath to `checkin-test.py` and then find the base TriBITS directory by going up 3 directories from there.  Originally, it went up only 2 directories (not accounting for `ci_support`).

**Comment by bartlettroscoe** [comment]
Please give the exact commands.  Are you symlinking Trilinos/checkin-test.py or Trilinos/cmake/tribits/ci_support/checkin-test.py?  What checkin-test.py arguments are you using?

**Comment by bartlettroscoe** [comment]
What is the exact error message you are getting with those commands?

**Comment by tjfulle** [comment]
If you look at the diff between the two versions, you can see that the original only looks for the configuration file 2 directories up from the real path of `checkin-test.py`.  It does not account for the `ci_support` directory and should lo k 3 directories up.  The bug is skipped if `checkin-test.py` is symlinked in to the same directory as the configuration file since the function also looks there.  If `checkin-test.py` is symlinked anywhere else, then the configuration file will not be found

**Comment by tjfulle** [comment]
It just occurred to me that `checkin-test.py` should also fail to find the configuration file if run directly from `cmake/tribits/ci_support` because it will only look 2 directories up instead of 3.

**Comment by bartlettroscoe** [comment]
We are no longer going to purse extending the checkin-test-sems.sh (or checkin-test.py) script for Trilinos.  See https://github.com/trilinos/Trilinos/issues/482#issuecomment-266124179.

Closing and won't fix.

**Comment by bartlettroscoe** [comment]
Just realized this is why I had to set --src-dir in checkin-test-sems.sh as part of commit https://github.com/trilinos/Trilinos/commit/d9acb8d52326d432692fda88e9c3f33a3ebc12b9.  I will go ahead and commit a fix directly to Trilinos first and remove --src-dir in checkin-tests-sems.sh.  That is a test that this change is needed and works.  I will then add an automated test on the TriBITS side to properly protect this with unit tests.

**Comment by bartlettroscoe** [comment]
@tjfulle, I rebased and amended your commit as 11c00e1.  I added a strong automated test to protect this in:

```
af01552 "Add test for directly running cmake/tribits/ci_support/checkin-test.py (#154)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Sat Dec 10 09:42:34 2016 -0700 (59 minutes ago)

M       test/ci_support/CMakeLists.txt
````

(I put in the wrong GitHub Issue ID).

I also had to fix the search order in 8caa3a2.

Thanks for bringing this up.  Sorry I closed this early in a rush last night to clean up after I was told to stop working on the Trilinos CI build.  I will continue to support the checkin-test.py script for myself and others who chose to use it.

Thanks again!

**Comment by bartlettroscoe** [comment]
@tjfulle, 

This should have been snapshotted into Trilinos and merged to 'develop' as of Trilinos commit:

```
commit 94dbad8467d68ae984cee54b03cf8a4426bb0d52
Merge: 76f8179 a3acfe1
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Sat Dec 10 10:02:42 2016 -0700

    Merge branch 'tribits_github_snapshot' into develop
    
    Build/Test Cases Summary
    Enabled Packages: Teuchos
    Disabled Packages: PyTrilinos,Claps,TriKota
    0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=123,notpassed=0 (2.46 min)
    1) MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX => Test case MPI_RELEASE_DEBUG_SHARED_PT_COMPLEX was not run! => Does not affect push readiness! (-1.00 min)
    Other local commits for this build/test group: a3acfe1, 76f8179
```

Can up please confirm that this issue is fixed now?

**Comment by bartlettroscoe** [comment]
Sorry, did not mean to close until @tjfulle confirmed this is fixed on the Trilinos slide.

**Comment by bartlettroscoe** [comment]
No complaints from @tjfulle in 25 days so assuming this this is fixed (and I have good unit tests for this).
