### ISSUE TITLE
Add Mercurial support to TribitsCTestDriveCore.cmake

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#17]
This issue is for adding mercurial support into native TriBITS cmake.
Initial scope is the ctest/TribitsCTestDriverCore.cmake, which supports git and svn.
Ross can elaborate on further version control usage which will also be addressed by this issue.

**Comment by bartlettroscoe** [comment]
Given that SCALE at ORNL is moving to git soon, is there any reason to keep this issue open?
