### ISSUE TITLE
Add TriBITS support for new DISABLED test property

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#173]
**Description:**

Kitware is adding a new `DISABLED` test property to CMake/CTest to allow the disabling of tests but do so in a way that the disabled test is visible in local testing and on CDash but not send out CDash failure emails or report failure locally.  This work is being tracked in the protected GitLab issue:

* https://gitlab.kitware.com/snl/project-1/issues/11

This story is to track the TriBITS changes needed to support this new feature in TriBITS.

**Tasks:**

0. Get trial changes in place to test out new `DISABLED` test property to help drive https://gitlab.kitware.com/snl/project-1/issues/11 [Done]

1. Start from scratch and add var `${PROJECT_NAME}_USE_CTEST_PROPERTY_DISABLED` to update TRIBITS_ADD_TEST() and TRIBITS_ADD_ADVANCED_TEST() and get unit tests working for `${PROJECT_NAME}_USE_CTEST_PROPERTY_DISABLED=TRUE` or `FALSE` (or just undefined).

2. Add `DISABLED` input option to `TRIBITS_ADD_ADVANCED_TEST()` and `TRIBITS_ADD_TEST()` and have it disable the test as well.

3. Add automatic set default `${PROJECT_NAME}_USE_CTEST_PROPERTY_DISABLED=TRUE` for CMake versions >= 3.10.

4. Test against new and older versions of CMake/CTest and push to TriBITS 'master' branch.

**Comment by bartlettroscoe** [comment]
This work is in progress and changes will be managed on the topic branch:

* https://github.com/TriBITSPub/TriBITS/tree/single-submit-and-disabled-tests-8-11

for now in coordination with Kitware contractors.

**Comment by bartlettroscoe** [comment]
I updated the branch:

* https://github.com/TriBITSPub/TriBITS/tree/single-submit-and-disabled-tests-8-11

to make the tests all pass.  However, I am likely going to need to start from scratch in order to push this to 'master' (see below conversation).

----

**DETAILED NOTES:**

Darn it, the unit tests for the old `<test_name>_DISABLE` flag never got updated and are failing on the branch:


* https://github.com/TriBITSPub/TriBITS/tree/single-submit-and-disabled-tests-8-11

I need to fix these tests and I need to address the problem of switching behavior depending on if the DISABLED test property is supported or not.  How can I do that?  I could do this with a variable like `TRIBITS_USE_TEST_PROPERTY_DISABLED`.  But I would really like to determine if the DISABLED test property was supported automatically.  Is there a way to do this?  In any case, for now, I will just add `TRIBITS_USE_TEST_PROPERTY_DISABLED` and make it off by default.  Then later, we can turn it on automatically if a sufficient CMake version is found.

This is going to be very messy in the code.  This is too bad really.  I wish I would have done this from the very beginning.  Now I am going to have to go back and revive the old code and call it based on `TRIBITS_USE_TEST_PROPERTY_DISABLED`.

Darn, my commit also did not take care of TRIBITS_ADD_ADVANCED_TEST() either.

Given all of this, I just want to get these unit tests passing.  Then later I will go back and start over and do this right.  I really just want to get on with #183 so that we can drive that forward.

Therefore, for now, I will just update the unit tests for the hard-coded DISABLED test property and worry about doing the right thing once the DISABLED test property support is pushed to the CMake/CTest and CDash git repos.

**Comment by bartlettroscoe** [comment]
Note, the updated branch is:

* https://github.com/TriBITSPub/TriBITS/tree/disabled-test-property-173

**Comment by bartlettroscoe** [comment]
@rppawlo and I discussed this yesterday.   I think the strategy that he likes is:

Add a new `DISABLED <msg>` argument to `tribits_add[_advanced]_test()` that if set, will set the ctest property `DISABLED` set like:

```
tribits_add_test(square_mess_bc
  DISABLED "Disabled because feature X is currently broken")
```

During configure, it will show the `DISABLED` property printed to STDOUT for the test getting added  showing output like:

```
-- PanzerAdaptersSTK_square_mesh_bc_MPI_4: Added test (BASIC, NUM_MPI_PROCS=4, PROCESSORS=4, DISABLED)!
--   => Disabled because feature X is currently broken
```

That way, one can see that the test is disabled at configure time, when the tests are run, and when posted to CDash.

He is going to make the modifications and post a PR for what he wants.

I think as part of this, I think we should also add the `tribits_add[_advanded]_test()` argument `DISABLE` which will do the same thing as the current `<fullTestName>_DISABLE` variable and allow a user to set this to a string like:

```
tribits_add_test(square_mess_bc
  DISABLE "Disabled because feature X is currently broken")
```

and allow setting:

```
   -D <fullTestName>_DISABLE="Disabled because feature X is currently broken"
```

which also evaluates to true.

But this will print to cmake STDOUT:

```
-- PanzerAdaptersSTK_square_mesh_bc_MPI_4: NOT added because PanzerAdaptersSTK_square_mesh_bc_MPI_4_DISABLE="Disabled because feature X is currently broken"
```

But in that case, the test is never seen by CTest or CDash.

There are use cases for either of these two modes so we can let the user decide which approach they want to use.

@rppawlo,

Does this sound okay?

**Comment by bartlettroscoe** [comment]
@rppawlo,

I updated the [above comment](https://github.com/TriBITSPub/TriBITS/issues/173#issuecomment-521694122) to add a `REMOVE_FROM_CTEST` argument as well and also support a `<fullTestName>_REMOVE_FROM_CTEST` variable as well (and deprecate `<fullTestName>_DISABLE`).

And come to think of it, it would be nice to have support for a `<fullTestName>_DISABLED` variable so a user could set the `DISABLED` property on a test for a specific build without having to edit the CMakeLists.txt file.

I will take care of all of this once you post your PR.

Thanks for taking this on!

**Comment by rppawlo** [comment]
PR for this capability is #292

**Comment by bartlettroscoe** [comment]
PR #292 is merged to TriBITS GitHub 'master' and Trilinos/Trilinos#5895 will merge this to Trilinos GitHub 'develop'.  After that, this should be done.

Putting in review.

**Comment by bartlettroscoe** [comment]
@rppawlo,

Have you had a chance to use what was merged in trilinos/Trilinos#5895 yet?  Can we close this issue?

**Comment by rppawlo** [comment]
yes - its working. We can close. Thanks!

**Comment by bartlettroscoe** [comment]
@rppawlo said:

> yes - its working. We can close. Thanks!

Thanks!
