### ISSUE TITLE
Implement CMake performance tips to reduce configure times

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#18]
This issue will address implementation of core cmake performance tips referenced at: http://www.cmake.org/Wiki/CMake_Performance_Tips
I have already implemented the include guards in lefebvre/TriBITS fork and seen a 10 second reduction in a 5 minute configuration of SCALE/Exnihilo/Trilinos(243 SE packages).

**Comment by bartlettroscoe** [comment]
@lefebvre, given that the newer versions of CMake configure very fast (i.e. patched CMake 3.3.2 and unpatched CMake 3.4.1 reconfigure VERA 6x faster than 2.8.11), do we need to do much more with configure performance?  The real savings will happen when I get around to implementing #63.

**Comment by bartlettroscoe** [comment]
I am going to close this.  With newer versions of CMake (such as the patched CMake 3.3.2 installed with install-cmake.py), the configure speed is very fast.  If this is not the case, please let me know but CASL VERA now reconfiugres and generates the coupled code package Tiamat in less than 30 seconds (which used to take about 3 minutes).
