### ISSUE TITLE
  TRIBITS_ADD_ADVANCED_TEST puts in an extra TRUE in OVERALL_WORKING_DIRECTORY

### ISSUE THREAD

**Issue by bathmatt** [TriBITSPub/TriBITS#180]
If I add a test as follows

```
TRIBITS_ADD_ADVANCED_TEST(
    ${IN_TEST_NAME}
    OVERALL_WORKING_DIRECTORY TEST_NAME
```

I get a cmake file that says
Drekar_plasma_oscillation_rtc_2D.cmake:SET(OVERALL_WORKING_DIRECTORY "TEST_NAMETRUE")

Why did it add the TRUE at the end of TEST_NAME?

**Comment by bartlettroscoe** [comment]
Never saw that before.  Can I see the full function call?  Can you push this to a branch that I can see (perhaps inside SNL SRN)?

**Comment by bathmatt** [comment]
It is in trilinos' git develop that I'm seeing this.

```

FUNCTION(DREKAR_ADD_EXODIFF_TEST IN_TEST_NAME IN_EXECUTABLE
IN_INPUT_XML_FILE IN_OUTPUT_EXO IN_GOLD_STANDARD_EXO IN_EXODIFF_FILE)

  IF (${PROJECT_NAME}_VERBOSE_CONFIGURE)
    MESSAGE("\nDREKAR_ADD_EXODIFF_TEST: ${IN_TEST_NAME}\n")
  ENDIF()
MESSAGE("\nDREKAR_ADD_EXODIFF_TEST: ${IN_TEST_NAME}\n")
  TRIBITS_ADD_ADVANCED_TEST(
    ${IN_TEST_NAME}
    OVERALL_WORKING_DIRECTORY "TEST_NAME"
    SKIP_CLEAN_OVERALL_WORKING_DIRECTORY TRUE
    TEST_0 EXEC ${IN_EXECUTABLE} NOEXEPREFIX NOEXESUFFIX
      ARGS  --i=${IN_INPUT_XML_FILE}
      PASS_REGULAR_EXPRESSION "Drekar run completed."
    TEST_1 EXEC ${SEACAS_BINARY_DIR}/applications/epu/epu NOEXEPREFIX
NOEXESUFFIX
      ARGS  "-auto" "${IN_OUTPUT_EXO}.${MPI_EXEC_MAX_NUMPROCS}."
      NUM_MPI_PROCS 1
    TEST_2 EXEC ${SEACAS_BINARY_DIR}/applications/exodiff/exodiff
NOEXEPREFIX NOEXESUFFIX
      ARGS -file ${IN_EXODIFF_FILE} ${IN_OUTPUT_EXO}
${IN_GOLD_STANDARD_EXO}
      NUM_MPI_PROCS 1
  )

ENDFUNCTION()
```

**Comment by bartlettroscoe** [comment]
@bathmatt,

You need to change:

```
SKIP_CLEAN_OVERALL_WORKING_DIRECTORY TRUE
```

to

```
SKIP_CLEAN_OVERALL_WORKING_DIRECTORY
```

as documented at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-add-advanced-test

The way the parser used by this works is very strange but what it is doing is it is doing is removing the **option** `SKIP_CLEAN_OVERALL_WORKING_DIRECTORY` and then lumping `TRUE` with the **argument** `OVERALL_WORKING_DIRECTORY TEST_NAME TRUE`.

We need to add better checking for these arguments.  We got that parser from someone else back in 2008 before I even started working with CMake.  Now that CMake provides a native parser function:

* https://cmake.org/cmake/help/v3.8/command/cmake_parse_arguments.html#command:cmake_parse_arguments

we might look into using that to see if it does something more sane (and might even go faster).

**Comment by bartlettroscoe** [comment]
@bathmatt, is this fixed on your end?  Can I close this Issue?

BTW, I created #181 to replace the input function parser which might help catch and report problems like this a little better.

**Comment by bathmatt** [comment]
Thanks...

**Comment by bartlettroscoe** [comment]
> Thanks...

Closing as complete after confirmation from @bathmatt.
