### ISSUE TITLE
How to submit build to different CDash group from a CTest -S script with TriBITS

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#189]
I am submitting this question from the below email as a GitHub issue question so that we can archive the answer for other people to see as well.  (Seems like the best thing to do since there is some good info in this response.)

**CC:** @william76, @jwillenbring, @bmpersc 

----

Hi Ross,

Jim and I are working on getting my GCC 4.9.3 and GCC 4.7.2 Warnings-as-errors tests on ASCIC moved over to the Specialized track.

My initial attempt was to just change the value of the CTEST_TEST_TYPE variable in my CMake script to “Specialized” from “Experimental”.  Unfortunately, this didn’t result in the builds showing up on the Specialized track on CDash.

Brent and I discussed this on Monday at the SEMS stand-up and he mentioned that there was something special about the Nightly and Experimental tracks that let this trick work but for different tracks there is something more to do that might affect Tribits.

When you have an opportunity, can you send me some pointers about where to look to get my tests moved over to the new track?

Thanks!

  -William

**Comment by bartlettroscoe** [comment]
@william76,

@bmpersc may know more about this than myself since it looks like he actually wrote the original code for this feature way back in the Trilinos commit:

```
1f4b3a9 "     SUMMARY:  Add the ability to change the dashboard track"
Author: Brent M. Perschbacher <bmpersc@sandia.gov>
Date:   Tue Sep 8 19:40:38 2009 +0000 (8 years ago)

M       cmake/ctest/TrilinosCTestDriverCore.cmake
M       cmake/ctest/drivers/s909348/ctest_mac_nightly_mpi_release_s909348.cmake
M       cmake/ctest/drivers/s909348/ctest_mac_nightly_serial_release_s909348.cmake
M       cmake/ctest/drivers/trilinos-test/ctest_linux_nightly_mpi_release_shared_trilinos-test.cmake
M       cmake/ctest/drivers/trilinos-test/ctest_linux_nightly_mpi_release_trilinos-test.cmake
M       cmake/ctest/drivers/trilinos-test/ctest_linux_nightly_serial_release_trilinos-test.cmake
```

But given what I see in the current implementation of that file (which is the same as @bmpersc had it, only the file moved), setting:

```
SET(Trilinos_TRACK Specialized)
```

in the top-level CTest -S driver script file should result in that build being sent to the CDash group “Specialized”.

Looking at:

* https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake#L777

you will see that `${${PROJECT_NAME}_TRACK}` is the second argument to `CTEST_START()`:

```
CTEST_START(${CTEST_TEST_TYPE} TRACK ${${PROJECT_NAME}_TRACK})
```

Looking at:

* https://cmake.org/cmake/help/v3.3/command/ctest_start.html

you see that the “Model” and the “Track” can be different (as in this case) but by default, “Model” is used for “Track” if the `TRACK`  argument is missing.

I can’t find any CTest or CMake documentation that explains this very well but the “Model” (the first argument to ctest_start()) should be confined to “Nightly”, “Experimental”, or “Continuous” (at least I have never seen anything else used for this).  But the “Track” can be any name that matches a “Group” for the target CDash project (I don’t know why CTest and CDash use different names for the same concept but they do and it is confusing).

Let me know if you have other questions about this.

**Comment by william76** [comment]
@bartlettroscoe 
CC: @bmpersc 

Thanks for the information!  I believe I have it working now.  Here's what I did:

Setting `Trilinos_TRACK` to "Specialized":

`SET(Trilinos_TRACK Specialized)`

alone isn't sufficient because Tribits sets the default value of `CTEST_TEST_TYPE` to "Experimental".  Inside [cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake](https://github.com/trilinos/Trilinos/blob/master/cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake#L406) there is a test that will force `${PROJECT_NAME}_TRACK` to Experimental if `CTEST_TEST_TYPE` is Experimental.

I changed both CTEST_TEST_TYPE and Trilinos_TRACK to Specialized in my test.
```
SET(CTEST_TEST_TYPE Specialized)  
SET(Trilinos_TRACK Specialized)
```
I just kicked them off in Jenkins but they appear to be doing the right thing and posting results to the [Specialized track on CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos##Specialized).

**Comment by bartlettroscoe** [comment]
> I changed both CTEST_TEST_TYPE and Trilinos_TRACK to Specialized in my test.
> 
> SET(CTEST_TEST_TYPE Specialized)  
> SET(Trilinos_TRACK Specialized)

I have no idea what setting the ctest_start() "Model" argument to "Specialized" will do.  I think we would need to dig into the CTest source code to figure that out.  Or, we could just ask the people at Kitware what the ctest_test() "Model" argument is supposed to do, what values it is allowed to take on, and what that means for ctest and cdash.  None of that is documented, for example, at:

* https://cmake.org/cmake/help/v3.8/command/ctest_start.html

(I will send a separate email to the Kitware people to ask them.)

> Setting Trilinos_TRACK to "Specialized":
>
> ```
> SET(Trilinos_TRACK Specialized)
> ```
> alone isn't sufficient because Tribits sets the default value of CTEST_TEST_TYPE to "Experimental".

That is unfortunate.

What if we just replaced this more complex block of code:

```
  # The default track to send the build to. This can be changed to send
  # the data to a different nightly grouping on the dashboard.
  # If the test type is set to Experimental though the track is forced
  # to "Experimental" this is so that we can have experimental tests
  # on branches.
  IF(${PROJECT_NAME}_TESTING_TRACK)
    SET(${PROJECT_NAME}_TRACK_DEFAULT ${${PROJECT_NAME}_TESTING_TRACK})
  ELSE()
    SET(${PROJECT_NAME}_TRACK_DEFAULT "")
  ENDIF()
  print_var(${PROJECT_NAME}_TRACK_DEFAULT)
  SET_DEFAULT_AND_FROM_ENV(${PROJECT_NAME}_TRACK "${${PROJECT_NAME}_TRACK_DEFAULT}")
  IF(CTEST_TEST_TYPE STREQUAL "Experimental" OR CTEST_TEST_TYPE STREQUAL "EXPERIMENTAL")
    SET(${PROJECT_NAME}_TRACK "Experimental")
    MESSAGE("-- Test type is Experimental. Forcing ${PROJECT_NAME}_TRACK to Experimental")
    PRINT_VAR(${PROJECT_NAME}_TRACK)
  ENDIF()
```

with something a little more straightforward:

```
#
# Set the targeted testing track/group on CDash where the build/test results will go.
#

IF (CTEST_TEST_TYPE STREQUAL "Experimental")
  # Always make the default testing track "Experimental" if the testing model is "Experimental"
  SET(${PROJECT_NAME}_TESTING_TRACK_DEFAULT ${CTEST_TEST_TYPE})
ELSEIF (NOT "${${PROJECT_NAME}_TESTING_TRACK_DEFAULT}" STREQUAL "")
  # Use the default testing track already set
ELSE()
  # Otherwise, a default track is not explicitly set so use the selected testing model
  # (e.g. 'Nightly', 'Continuous') for the default testing track on CDash
  SET(${PROJECT_NAME}_TESTING_TRACK_DEFAULT ${CTEST_TEST_TYPE})
ENDIF()

SET_DEFAULT_AND_FROM_ENV(${PROJECT_NAME}_TESTING_TRACK
  ${${PROJECT_NAME}_TESTING_TRACK_DEFAULT})
```

and then we can update files like Trilinos/Version.cmake to set:

```
SET(Trilinos_TESTING_TRACK_DEFAULT "Nightly Release 12.10")
```

instead of:

```
SET(Trilinos_TESTING_TRACK "Nightly Release 12.10" CACHE INTERNAL "")
```

?

That is the idiom that the rest of the project-level variables in TriBITS has been going with as documented, for example, at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-global-project-settings

We can then document how to correctly set `CTEST_TEST_TYPE` and `${PROJECT_NAME}_TESTING_TRACK` in:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-ctest-driver

There is very little code that sets the testing track and it is just ctest -S driver code that messes with this.  Therefore, I think the non-backward-compatible change this would have would be easy to adjust to.

While we are at it, note that the variable `CTEST_TEST_TYPE`  (which is just the ctest_start() model and the default cdash track) was make up in the very early days of TriBITS when Trilinos was just starting to use CMake/CTest/CDash.  The prefix `CTEST_` is a very bad prefix for this because it gives the impression that this is a built-in CTest variable (which it is not).  Really we should change this to something like `${PROJECT_NAME}_TESTING_MODEL` and deprecate the name `CTEST_TEST_TYPE` (or just remove it).  I think that would help avoid some confusion about what this is.

So, in summary, I am suggesting that we:

1) Change the name of `CTEST_TEST_TYPE` to `${PROJECT_NAME}_TESTING_MODEL` (adding `${PROJECT_NAME}_TESTING_MODEL_DEFAULT`).  (We can either deprecate the variable `CTEST_TEST_TYPE` or remove it all together.  I would prefer to just remove it since regular users never interact with this variable.)

2) Replace the current logic for setting `${PROJECT_NAME}_TRACK` with the new variable `${PROJECT_NAME}_TESTING_TRACK` (and `${PROJECT_NAME}_TESTING_TRACK_DEFAULT`) as described above.  (Note, the new logic will allow the user to set a testing track other than "Experimental" when the selected testing model is "Experimental".  That would allow the creation and usage of different experimental testing CDash tracks if one so desired.  I can think of examples of why you might want to have multiple experimental CDash tracks to better organize your experimental builds.)

3) Document the new variables `${PROJECT_NAME}_TESTING_MODEL` and `${PROJECT_NAME}_TESTING_TRACK` in the documentation for the `TRIBITS_CTEST_DRIVER()` function.

Any objections to making these changes?  This would break backward compatibility but it should impact very few people I think.  I think this would simplify the setup and usage of TriBITS CTest -S driver scripts.

**Comment by bartlettroscoe** [comment]
After some thought, I think we need to remove the usage of `CTEST_TEST_TYPE` but check to see if it is set and then exit with an error code if it is set by the user.  The hard error message will tell the user they need to switch over to set `${PROJECT_NAME}_TESTING_MODEL` or `${PROJECT_NAME}_TESTING_MODEL_DEFAULT`.  That way, users controlling any existing builds that I can't get to to fix (e.g. because they are on branches) will be notified that they need to update and how to update.

Without objection, I will create a new TriBITS issue to make these changes and then make them.

**Comment by jwillenbring** [comment]
I do not object to these changes.

**Comment by bartlettroscoe** [comment]
I sent some Kitware staff an email asking about the behaviors of ctest_test().  Below was the response from Zack G. at Kitware.

Basically, he was not sure what happens when you pass in the "Model" argument to be something other than 'Nightly', 'Continuous', or 'Experimental' but he guesses that it would be treated as 'Experimental'.

What is interesting is that setting the "Model" argument to "Specialized" has set the "Build Type" on CDash to "Specialized" as shown at:

* http://testing.sandia.gov/cdash/buildSummary.php?buildid=2862095

Therefore, it is still unclear what the "Model" argument does with CTest and CDash other than just set the "Build Type" on CDash to that value.  Does that argument actually change anything about the behavior of CTest or CDash?  I will ask them about this.

----

Subject: [EXTERNAL] What does the "Model" argument in ctest_start(Model ...) really mean and do?

On Wed, Apr 26, 2017 at 11:57 AM, Bartlett, Roscoe A <rabartl@sandia.gov> wrote:
> What does the “Model” argument in ctest_start(Model …) really do?  What values it is allowed to take on?
 
Valid models are Nightly, Experimental, or Continuous.  I think Nightly is the only option here that has special behavior.  It updates and sets its stamp to CTEST_NIGHTLY_START_TIME.

> how does this impact ctest and/or cdash?

On the CDash side, "model" is stored as the build's type.  This is distinct from what group a build belongs to, although all projects are created with default groups for Nightly, Experimental, and Continuous builds.

> What happens if you pass in a Model argument that is not one of the standard value? 

Without testing this, my hunch is that you would get sorted into the Experimental model by default.

I think you might be interested in the "Track" option.  This is documented on these pages:

https://cmake.org/cmake/help/latest/command/ctest_start.html
https://cmake.org/cmake/help/latest/manual/ctest.1.html

This allows you to specify what (arbitrary) group a build should belong to.

**Comment by bartlettroscoe** [comment]
The Trilinos "Clean" and "ATDM" builds do this so this should be a solved issue.

Closing as complete.

**Comment by bartlettroscoe** [comment]
Closing for real this time.
