### ISSUE TITLE
Implement Mercurial support in Python layer

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#19]
This issue will address all implementation of Mercurial in the Python layer.
Initial target is the checkin-test.py script. Ross can elaborate on any further python files which deal with version control.

**Comment by bartlettroscoe** [comment]
@lefebvre, is it still desighed to add Mercurial support to these TriBITS tools?  Have your projects moved to git yet?

**Comment by bartlettroscoe** [comment]
Closing since no response to comment [above](https://github.com/TriBITSPub/TriBITS/issues/19#issuecomment-284125833) and it looks like git has completely taken over and more and more projects have switched to git (including SCALE).

Closing as wontfix
