### ISSUE TITLE
Can SOURCE_DIR_OVERRIDE be absolute?

### ISSUE THREAD

**Issue by ibaned** [TriBITSPub/TriBITS#194]
@bartlettroscoe recently informed me about this feature, so naturally I'm pushing the boundaries of it:
```
-- NOTE: Kokkos_SOURCE_DIR_OVERRIDE='/home/daibane/src/kokkos' is overriding default path 'packages/kokkos'
CMake Error at cmake/tribits/core/utils/MessageWrapper.cmake:80 (MESSAGE):
  Error: The pacakge 'Kokkos' was given an absolute directory
  '/home/daibane/src/kokkos' which is *not* under the project's source
  directory '/home/daibane/src/Trilinos/'!
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake:490 (MESSAGE_WRAPPER)
  cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake:1445 (TRIBITS_PROCESS_PACKAGES_AND_DIRS_LISTS)
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:160 (TRIBITS_READ_PACKAGES_PROCESS_DEPENDENCIES_WRITE_XML)
  cmake/tribits/core/package_arch/TribitsProject.cmake:93 (TRIBITS_PROJECT_IMPL)
  CMakeLists.txt:93 (TRIBITS_PROJECT)

```
Is there a strong reason for this restriction, or could it be relaxed? It would certainly be convenient for me if the path could be absolute, and since the `../kokkos` workaround is accepted, I'll just use that.

**Comment by bartlettroscoe** [comment]
> Is there a strong reason for this restriction, or could it be relaxed? 

Currently, this is a strong restriction (hence the check and the error message).  The issue is that we would need to add the ability to specify a different relative directory path for the package under the build tree.   (Not the hardest thing but would take careful testing and refactoring.)

Can you just do something like:

```
$ cd Trilinos/
$ ln -s home/daibane/src/kokkos .
```

?

I already put in the ignore `/kokkos/` in Trilinos/.gitignore.

Let me know if that does not work for you.

**Comment by bartlettroscoe** [comment]
>  since the ../kokkos workaround is accepted, I'll just use that.

Hum, that might be a defect (in not catching and disallowing this).  I think this will create the build directory for Kokkos beside the build directory for Trilinos.  That is a bit strange and would likely confuse people (it would confuse me).

**Comment by ibaned** [comment]
Okay, the parallel build directory structure seems to be a good rationale for this restriction. I'll find a convenient way to make it a subdirectory, probably with a symbolic link as you suggest. Thanks!
