### ISSUE TITLE
Testing a specific version of Trilinos

### ISSUE THREAD

**Issue by jwillenbring** [TriBITSPub/TriBITS#214]
@bmpersc @william76

(this is more of a question than an issue, but I don't have permission to apply that label)

For the Trilinos pull request testing, we need to have the ability to test a very specific version of Trilinos. For example, a driver Jenkins job looks and finds a pull request and identifies the source and target branches for the pull request (ex some branch from someone's fork is the source, and develop the target), then we also need to make sure we are using consistent specific SHAs from each branch. For example, we don't want 3/4 pull request builds testing against one version of develop and the other another version of develop as this could make error differences confusing. The same could be said about if the user updates their pull requests while some jobs are running and one is still queued up. So 3 builds fail in that case, and the 4th one is fixed, or the other way around. 

Plus, we want to make sure we are testing the latest version of the pull request for all builds. For that reason, if during pull request testing someone updates a pull request with a new set of commits, when the jobs return, even if things pass, we invalidate the testing because it tested an old version of the pull request. We cannot assume that the new version of the pull request would pass, and likewise if someone submitted new commits, we certainly don't want to push an obsolete version of a pull request to develop.

So it's not just some specific version of some branch we want to ultimately test on, it is a version where  someone's branch from their fork is merged on top of a specific version of develop. Does TriBITS allow us to set up the version we want to test like this? I know that generally you have a version of Trilinos that then clones another repo to actually test (the test scripts come from the first, and the source code of the second is actually tested).

**Comment by bartlettroscoe** [comment]
Sorry, just saw this (I did not get a GitHub email).  ...

It looks like the raw `CTEST_UPDATE()` command supports a custom update command specified by the var `CTEST_GIT_UPDATE_OPTIONS` as described in:

* https://cmake.org/cmake/help/v3.9/manual/ctest.1.html#ctest-update-step

Please just set that var in your CTest -S driver script to something like:

```
SET(CTEST_GIT_UPDATE_OPTIONS "git checkout ${THE_SHA1}")
```

and see what happens.  Let me know what your experimentation shows.

But getting this to work for multiple git repos will take more work.

**Comment by bartlettroscoe** [comment]
Closing since no response to my [above](https://github.com/TriBITSPub/TriBITS/issues/214#issuecomment-321908781) comment in 17 months.  Closing as invalid.
