### ISSUE TITLE
Trilinos Release 12.12 testing not testing release branch

### ISSUE THREAD

**Issue by jwillenbring** [TriBITSPub/TriBITS#215]
@william76 @bmpersc 

This is a sort of follow-on to #211 in that after that change was applied, we are now not pulling the right branch for the Trilinos release 12.12 testing. The actual version that is being tested is the develop branch, as can be seen by the update output for the build:

[https://testing.sandia.gov/cdash/viewUpdate.php?buildid=3045604](https://testing.sandia.gov/cdash/viewUpdate.php?buildid=3045604)

If you look in git log, the first commit referenced is:

commit 4eed915a4bca8fbad6ede345da3846398d1101ce
...
Date:   Tue Aug 8 15:50:05 2017 -0600

    Testing: update CUDA tests on geminga
    
    Add CUDA and OpenMPI version to label.

Which is was applied to the develop branch yesterday and should not be part of release testing. This has worked for testing previous releases of Trilinos. Any insights into what changed to impact this would be appreciated.

The specific repo info from the build is (thanks @bmpersc):

the repo that jenkins clones is at dab74e0731527b932c86d83c1df14809617e4dbd which is the tip of the trilinos-release-12-12-branch

the repo that tribits cloned to test is at: "ref: refs/heads/develop”

**Comment by bartlettroscoe** [comment]
I would have to see the full output being produced by the `ctest -S <script>` command.  Can you please attach that?  It should be obvious what it is doing from that.  And then there is always `MESSAGE()` print statements to debug the problem.  Please try to chip in and see if you can help figure it out.

**Comment by jwillenbring** [comment]
@william76 - can you attach the output @bartlettroscoe requested? I looked on ascic jenkins but I didn't see the job that is trying to test 12.12.

**Comment by jwillenbring** [comment]
@bmpersc @william76 @bartlettroscoe When the driver dashboard is involved, where would I find the output of test -S <script> for the individual scripts? I found the job on Jenkins now (looked on wrong build farm). Everything in the Jenkins output appears to be at the driver level and basically nothing seems to happen at all below that.

**Comment by bmpersc** [comment]
@jwillenbring the release testing still uses the TDD testing system so it should show up on the TrilinosDriver dashboard. It does seem like that is working right now which is good, but I recall checking for that initially and it wasn't there.  There was a useful error that reported that git was choking on the -B option being given to checkout. This was something we'd run into with the develop branch and just updated git to address it. I just made the same change to the release testing job and I think that will probably fix the existing issue. 

If you are interested, the most recent TDD reports for the release 12.12 testing as of this comment is at: https://testing.sandia.gov/cdash/viewTest.php?onlypassed&buildid=3125673

**Comment by bartlettroscoe** [comment]
So does this mean that this is fixed?  Can we close this issue?

NOTE: The TDD system should not be used going forward and should be replaced with either Jenkins or with a new system built with raw CMake/CTest/CDash (that is much simpler and can be unit tested).

**Comment by bmpersc** [comment]
@bartlettroscoe I'd like to see how the job behaves tonight before saying this is fixed.

**Comment by bartlettroscoe** [comment]
Judging from the fact that `Nightly Release 12.12` builds are showing up on CDash at:

* https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2018-03-15&filtercount=0&showfilters=1

I will assume this issue is resolved.

Thanks for reporting.
