### ISSUE TITLE
Get checkin-test script to work with ninja generator

### ISSUE THREAD

**Issue by rppawlo** [TriBITSPub/TriBITS#219]
This story is to add an option `--use-ninja` to make the checkin-test.py script set `-G Ninja` in the do-configure.base script and then to run `ninja -j<N>` instead of `make -j<N>`.  That should all that needs to be done to get the checkin-test.py script to work with ninja.

**Comment by bartlettroscoe** [comment]
Okay, I will address this as part of the other Ninja-related work under:

* https://software-srn.sandia.gov/jira/browse/ATDV-14

**Comment by bartlettroscoe** [comment]
@rppawlo, if you are using the dummy makefiles, does it not just automatically work with Ninja?  The only thing that I think would not automatically work would be that ninja would ignore the `-j<N>` argument passed to `make -j<N>`.

**Comment by rppawlo** [comment]
Maybe I am doing something wrong. I added the extra flag to change the generator to ninja:

```
./checkin-test-sems.sh --src-dir='/home/rppawlo/Trilinos' --allow-no-pull --configure --extra-cmake-options='-G Ninja'
```

and get a configure failure:

```
[rppawlo@gge BUILD]$ more  MPI_RELEASE_DEBUG_SHARED_PT/configure.out 
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
[rppawlo@gge BUILD]$
```

**Comment by bartlettroscoe** [comment]
This is likely a module issue.  Try doing:

```
$ export PATH=<base_to_ninja>/bin:$PATH
```

If you use a module to load ninja, it will get unloaded when `source load_ci_sems_dev_env.sh` gets run.  When I did this I was able to run:

```
$ ./checkin-test-sems.sh --extra-cmake-options="-GNinja -DTrilinos_ENABLE_Fortran=OFF" \
  --allow-no-pull \
  --no-enable-fwd-packages --enable-all-packages=off --enable-packages=Teuchos \
  --configure
```

I got in the configure output:

```
-- CMAKE_GENERATOR='Ninja'
```

and it passed the configure.

However, if you want this to work, you have to use a new-enough version of CMake so that it will create the dummy makefiles automatically.

I can give exact instructions for how to use ninja with the checkin-test-sems.sh script but that is really a Trilinos issue, not a TriBITS issue.  So I can give those instructions to you offline or in a Trilinos GitHub issue.

We should leave this TriBITS issue to add an option `--use-ninja` to the checkin-test.py script which will work for any recent version of Ninja and CMake (but to have Fortran enabled, you will need to use Kitware's version of Ninja).

**Comment by rppawlo** [comment]
[tribits_ninja.patch.txt](https://github.com/TriBITSPub/TriBITS/files/1475980/tribits_ninja.patch.txt)

attached is a patch file to implement the flag --use-ninja in tribits. Note that using this for pushes to Trilinos will require the user to manually disable Fortran support unless using the kitware hacked verison of ninja. Here's the command:

--extra-cmake-options='-DTrilinos_ENABLE_Fortran:BOOL=OFF'

**Comment by bartlettroscoe** [comment]
@rppawlo, thanks for the patch.  I will need to add automated tests before I can push this.  Also, we will need to document that `--make-options=<make-options>` will be passed to  `ninja` as well.

Is it time critical to get this merged into the main TriBITS 'master' branch and snapshotted to Trilinos?  If so, I will get on this.

**Comment by rppawlo** [comment]
@bartlettroscoe Not critical unless there are more people that want to use it. I'm fine applying the patch to my local builds right now.

**Comment by bartlettroscoe** [comment]
This is done and pushed to TriBITS GitHub 'master' (see commit e8720eb).  I will snapshot to Trilinos soon.

**Comment by bartlettroscoe** [comment]
This has been snapshotted in the Trilinos commit trilinos/Trilinos@1eb7e31 and pushed to the Trilinos 'develop' branch.  I am now using this with the checkin-test-atdm.sh script for local testing of ATDM builds of Trilinos.

I am closing as complete.

@rppawlo, please let me know if you have any problems with this.

Sorry for the long delay in getting this done.  It just needed automated testing before it could be merged into the main TriBITS 'master' branch.

**Comment by bartlettroscoe** [comment]
Closing the issue as complete (for real this time).

**Comment by rppawlo** [comment]
Thanks @bartlettroscoe !
