### ISSUE TITLE
TriBITS imposes very low (3.2) minimum CUDA version.

### ISSUE THREAD

**Issue by mhoemmen** [TriBITSPub/TriBITS#222]
TriBITS currently imposes a very low (3.2) minimum CUDA version, in its find "TPL" CUDA function:

https://github.com/TriBITSPub/TriBITS/blob/c77e47dc9206b64b803a25728a8b5ce0ebf610bb/tribits/core/std_tpls/FindTPLCUDA.cmake#L62

Kokkos currently needs at least CUDA 7.0, and Trilinos needs at least CUDA 7.5.  Could it be possible for the code that invokes the find "TPL" CUDA function to specify the minimum version?

**Comment by bartlettroscoe** [comment]
>  Could it be possible for the code that invokes the find "TPL" CUDA function to specify the minimum version?

Yes, I think that could be done.  We could add a project-level CMake cache variable `${PROJECT_NAME}_CUDA_MIN_VERSION` with a project-specific default `${PROJECT_NAME}_CUDA_MIN_VERSION_DEFAULT` that would be added to the set of project-level vars:

*  https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-global-project-settings

Should be pretty easy.  The bulk of the work is just adding documentation.  Not sure how to add automated tests for TriBITS for this since you would need CUDA on your local system in order to test this.  Therefore, we may just need to manually test this with Trilinos and go with that.  It is **very** little actual code so the risk of breaking this in the future is low.

**Comment by mhoemmen** [comment]
@bartlettroscoe I'm not sure if it's a big deal.  The 3.2 min requirement may have come from the test code in FindTPLCUDA, that is now commented out.  Perhaps it would be better for individual packages to impose their own requirements by testing `CUDA_VERSION`.  This is what Tpetra does.

We could just take out the version requirement in TriBITS; would that be hard?  I mainly want to prevent Trilinos' users from getting confused by the 3.2 displayed min version.

**Comment by bartlettroscoe** [comment]
So, to be clear, you just want to remove '3.2' from the command `FIND_PACKAGE(CUDA 3.2 REQUIRED) `?

**Comment by mhoemmen** [comment]
@bartlettroscoe wrote:
> So, to be clear, you just want to remove '3.2' from the command `FIND_PACKAGE(CUDA 3.2 REQUIRED)`?

Yes, please.  It should be up to the project, not TriBITS, what minimum CUDA version to support.

Thanks!

**Comment by bartlettroscoe** [comment]
>  It should be up to the project, not TriBITS, what minimum CUDA version to support.

I did not write any of this code for CUDA so I am not sure how that module works.  Is there a way for a project to specify the minimum version for CUDA **without** passing the version into `FIND_PACKAGE(CUDA <min_version> REQUIRED)`?  I can't see it looking at:

* https://cmake.org/cmake/help/v2.8.11/cmake.html#module:FindCUDA

**Comment by mhoemmen** [comment]
Tpetra's CMake just errors out if `CUDA_VERSION` is less than 7.5:

https://github.com/trilinos/Trilinos/blob/03574911fb6d783f086dc052772f9ade7b4d1566/packages/tpetra/CMakeLists.txt#L31

I don't know a way to do this declaratively.  It would have to be per package too, since Kokkos has different requirements than downstream packages.  It also depends on project options -- e.g., MueLu's "Kokkos refactor" option may use `KOKKOS_LAMBDA` heavily.

I'll be happy if we just get rid of the 3.2 minimum version requirement print-out ;-) .  It's way too small and thus misleading for users.  I can submit a PR for that if you would like.

**Comment by bartlettroscoe** [comment]
As of Trilinos commit:

```
commit 20057a5ea22fb47a039c4f697b9b3a16b36b97d6
Merge: 0357491 c3c4439
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Sat Sep 9 09:46:35 2017 -0600

    Merge branch 'tribits_github_snapshot' into develop
    
    * Fixes all-at-once 'dashboard' target (TriBITSPub/TriBITS#183)
    * Removes min CUDA version 3.2 (TriBITSPub/TriBITS#222)
```

just pushed, CUDA 3.2 should no longer be the min version.

@mhoemmen, please confirm on your end.  Otherwise, I will put into review and then close in a few days.

**Comment by mhoemmen** [comment]
@bartlettroscoe Thanks Ross! :-D  I'll try it out!

**Comment by mhoemmen** [comment]
@bartlettroscoe Confirmed; Trilinos' CMake output no longer displays a minimum CUDA version, and it correctly diagnoses the build's `CUDA_VERSION` as 8.0.  Thanks!!!
