### ISSUE TITLE
Fortan Mangling error on Windows when compiler flags are set

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#23]
There is an issue with the config_tests/FortranMangling.cmake.
The issues stems from Windows variety of system libraries.
One can use /MD[d] /MT[d] /LD[d]  for linking their different libraries MSVCRT.lib, MSVCRTD.lib, LIBCMT.lib, LIBCMTD.lib.
CMake typically defaults to /MD for release and /MDd for debug.
If one needs a static build overriding all compiler flags with /MT[d] is necessary.
The FortranMangling.cmake doesn't pass the build type compiler flags through which usually results in duplicate defined symbols, because C/C++ will link against LIBCMT and Fortran will link agains MSVCRT.
This patch resolves the issue.

```
--- a/cmake/tribits/config_tests/FortranMangling.cmake    Thu Jul 17 15:26:06 2014 -0400
+++ b/cmake/tribits/config_tests/FortranMangling.cmake    Tue Sep 23 13:48:57 2014 -0400
@@ -99,7 +99,9 @@
         SET(F_FLAGS "${CMAKE_Fortran_FLAGS} ${${PROJECT_NAME}_EXTRA_LINK_FLAGS}")
         TRY_COMPILE(_fcmngl ${_fcmangledir_case} ${_fcmakelists} fmangle
           CMAKE_FLAGS "-DCMAKE_C_FLAGS:STRING=${C_FLAGS}"
+          "-DCMAKE_C_FLAGS_RELEASE:STRING=${CMAKE_C_FLAGS_RELEASE}"
           "-DCMAKE_Fortran_FLAGS:STRING=${F_FLAGS}"
+          "-DCMAKE_Fortran_FLAGS_RELEASE:STRING=${CMAKE_Fortran_FLAGS_RELEASE}"
           "-DCOMMON_DEFS=${COMMON_DEFS}"
           OUTPUT_VARIABLE _fcmngl_output
           )
```

**Comment by bartlettroscoe** [comment]
Jordan (@lefebvre),

Can you confirm that this issue has been resolved on your side?

**Comment by bartlettroscoe** [comment]
@lefebvre.  I am going to assume this is fixed given there was no response since July.
