### ISSUE TITLE
Semicolon separated path sets are not preserved in a ctest driver

### ISSUE THREAD

**Issue by prwolfe** [TriBITSPub/TriBITS#234]
We are passing -DUMFPACK_INCLUDE=PATHA;PATHB;PATHC to a ctest instance (see https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/SierraIntegrationCandidateTesting/job/Trilinos_parameter_experiment_sierra/416/consoleFullfor an example.) The resulting final config that is reported to cmake instead looks like "-DUMFPACK_INCLUDE=PATHA" "PATHB" PATHC" with the result that only PATHA is actually applied (see .https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3180425).  I have confirmed that the semicolon separated list works properly when passed to cmake.

This is a regular build to support sierra and UMFPACK is needed for Amesos2.  If you have any questions let me know.

Thanks!

**Comment by bartlettroscoe** [comment]
@prwolfe,

When I go to link:

* https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/SierraIntegrationCandidateTesting/job/Trilinos_parameter_experiment_sierra/416/consoleFullfor

it says "Problem accessing /job/trilinos-folder/job/SierraIntegrationCandidateTesting/job/Trilinos_parameter_experiment_sierra/416/consoleFullfor. Reason: Not Found"

The commandline shown on CDash is shown below.

The issue with cmake is that handling of semicolons and spaces and array handling is very fragile. 

My advise is to put all of this info into into one or more *.cmake files with set() commands and then just point to those files.  You can see an example of that with:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/ctest/drivers/sems_ci/ctest_linux_mpi_debug_shared_pt_ci.sems.cmake

and the CDash output shows that, for example, at:

* https://testing.sandia.gov/cdash/viewConfigure.php?buildid=3183491

See the argument:

* `-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/MpiReleaseDebugSharedPtSettings.cmake,cmake/std/BasicCiTestingSettings.cmake`

There are many advantages to this approach and it solves this problem with CMake ";" and " ".

Please let me know if you have questions about this.

----

"/projects/sems/install/rhel6-x86_64/sems/utility/cmake/2.8.11/bin/cmake" "-DTrilinos_TRIBITS_DIR=/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/Trilinos/cmake/tribits" "-DCTEST_USE_LAUNCHERS:BOOL=1" "-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON" "-DTrilinos_WARNINGS_AS_ERRORS_FLAGS:STRING=" "-DTrilinos_ALLOW_NO_PACKAGES:BOOL=ON" "-DTrilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON" "-DTrilinos_DEPS_XML_OUTPUT_FILE:FILEPATH=" "-DTrilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON" "-DTrilinos_EXTRAREPOS_FILE:STRING=/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/Trilinos/cmake/ExtraRepositoriesList.cmake" "-DTrilinos_IGNORE_MISSING_EXTRA_REPOSITORIES:BOOL=ON" "-DTrilinos_ENABLE_KNOWN_EXTERNAL_REPOS_TYPE:STRING=None" "-DTrilinos_ENABLE_TESTS:BOOL=ON" "-DTrilinos_ENABLE_ShyLU_Node:BOOL=" "-DTrilinos_ENABLE_Amesos:BOOL=OFF" "-DTrilinos_ENABLE_Zoltan2:BOOL=OFF" "-DTrilinos_ENABLE_Ifpack:BOOL=OFF" "-DTrilinos_ENABLE_ML:BOOL=OFF" "-DTrilinos_PRE_REPOSITORIES=''" "-DTrilinos_EXTRA_REPOSITORIES=''" "-DCMAKE_BUILD_TYPE:STRING=release" "-DTrilinos_ENABLE_DEPENDENCY_UNIT_TESTS:BOOL=OFF" "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON" "-DBUILD_SHARED_LIBS:BOOL=ON" "-DTrilinos_ENABLE_CXX11=ON" "-DTrilinos_CXX11_FLAGS:STRING=--std=c++11" "-DTPL_ENABLE_BLAS:BOOL=ON" "-DTPL_ENABLE_LAPACK:BOOL=ON" "-DSuperLU_INCLUDE_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.9.3/base/include" "-DSuperLU_LIBRARY_DIRS:PATH=/projects/sems/install/rhel6-x86_64/sems/tpl/superlu/4.3/gcc/4.9.3/base/lib" "-DSuperLU_LIBRARY_NAMES:STRING=superlu" "-DBoost_INCLUDE_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.9.3/base/include" "-DBoost_LIBRARY_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.9.3/base/lib" "-DBoostLib_INCLUDE_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.9.3/base/include" "-DBoostLib_LIBRARY_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/boost/1.55.0/gcc/4.9.3/base/lib" "-DHDF5_INCLUDE_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.9.3/openmpi/1.10.1/parallel/include" "-DHDF5_LIBRARY_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/hdf5/1.8.12/gcc/4.9.3/openmpi/1.10.1/parallel/lib" "-DNetcdf_INCLUDE_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.9.3/openmpi/1.10.1/parallel/include" "-DNetcdf_LIBRARY_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/netcdf/4.3.2/gcc/4.9.3/openmpi/1.10.1/parallel/lib" "-DZlib_INCLUDE_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.9.3/base/include" "-DZlib_LIBRARY_DIRS:FILEPATH=/projects/sems/install/rhel6-x86_64/sems/tpl/zlib/1.2.8/gcc/4.9.3/base/lib" "-DTPL_ENABLE_MPI:BOOL=ON" "-DMPI_BASE_DIR=/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.10.1" "-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF" "-DTPL_ENABLE_SuperLU=OFF" "-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON" "-DTeuchos_ENABLE_COMPLEX:BOOL=ON" "-DTrilinos_ENABLE_OpenMP:BOOL=OFF" "-DTPL_ENABLE_HWLOC:STRING=OFF" "-DTPL_ENABLE_CUDA:STRING=OFF" "-DFEI_AZTECOO:BOOL=ON" "-DTrilinos_ENABLE_AztecOO:BOOL=ON" "-DTrilinos_ENABLE_EpetraExt:BOOL=ON" "-DKokkos_ENABLE_Pthread:BOOL=ON" "-DKokkos_ENABLE_Cuda_UVM:BOOL=OFF" "-DKokkos_ENABLE_OpenMP:BOOL=OFF" "-DMETIS_INCLUDE_DIRS=/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.9.3/openmpi/1.10.1/64bit_parallel/include" "-DMETIS_LIBRARY_DIRS=/projects/sems/install/rhel6-x86_64/sems/tpl/parmetis/4.0.3/gcc/4.9.3/openmpi/1.10.1/64bit_parallel/lib" "-DNOX_ENABLE_ABSTRACT_IMPLEMENTATION_THYRA:BOOL=OFF" "-DNOX_ENABLE_EPETRA:BOOL=ON" "-DTpetra_INST_SERIAL:BOOL=ON" "-DTpetra_INST_OPENMP:BOOL=OFF" "-DTpetra_INST_PTHREAD:BOOL=ON" "-DTpetra_INST_CUDA:BOOL=OFF" "-DTrilinos_INST_COMPLEX_DOUBLE:BOOL=ON" "-DTpetra_INST_COMPLEX_FLOAT:BOOL=OFF" "-DTpetra_INST_INT_INT:BOOL=ON" "-DTpetra_INST_INT_LONG:BOOL=ON" "-DTpetra_INST_INT_LONG_LONG:BOOL=OFF" "-DTpetra_INST_FLOAT:BOOL=OFF" "-DTpetra_INST_DOUBLE:BOOL=ON" "-DTpetraCore_ENABLE_TSQR:BOOL=ON" "-DTrilinos_ENABLE_TpetraTSQR:BOOL=ON" "-DTrilinos_ENABLE_Tpetra:BOOL=ON" "-DMueLu_ENABLE_Epetra=OFF" "-DMueLu_ENABLE_Tpetra=ON" "-DAmesos2_ENABLE_Epetra=OFF" "-DCMAKE_CXX_FLAGS:STRING=-ftemplate-depth-128 -std=c++0x -Wall -Wno-clobbered -Wno-vla -Wno-narrowing -Wno-pragmas -Wno-unknown-pragmas -Wno-delete-non-virtual-dtor -Wno-unused-local-typedefs -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-type-limits -Wno-missing-field-initializers -Wno-array-bounds -Wno-delete-non-virtual-dtor -Wno-literal-suffix -O2 -finline-functions -Wno-inline -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-strict-overflow -Werror" "-DCMAKE_C_FLAGS:STRING=-Wall -Wno-unused-but-set-variable -Wno-clobbered -Wno-vla -Wno-narrowing -Wno-pragmas -Wno-unknown-pragmas -Wno-unused-local-typedefs -Wno-ignored-qualifiers -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-type-limits -Wno-missing-field-initializers -Wno-array-bounds -O2 -finline-functions -Wno-inline -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-function -Wno-maybe-uninitialized -Wno-strict-overflow -Werror" "-DCMAKE_Fortran_FLAGS=-finline-functions -Wno-inline -fno-second-underscore -Wall -Wno-unused-variable -Werror -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-dummy-argument -Wno-maybe-uninitialized -Wno-conversion" "-DTPL_ENABLE_UMFPACK:BOOL=ON" "-DUMFPACK_INCLUDE_DIRS:PATH=/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/UMFPACK/Include" "/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/AMD/Include" "/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/UFconfig" "-DUMFPACK_LIBRARY_DIRS:PATH=/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/UMFPACK/Lib" "/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/AMD/Lib" "-DUMFPACK_LIBRARY_NAMES:STRING=umfpack" "amd" "-DTPL_ENABLE_AMD:BOOL=ON" "-DAMD_INCLUDE_DIRS:PATH=/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/AMD/Include" "/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/UFconfig" "-DAMD_LIBRARY_DIRS:PATH=/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/SuiteSparse/AMD/Lib" "-DAMD_LIBRARY_NAMES:STRING=amd" "-DTrilinos_ENABLE_Amesos2:BOOL=ON" "-GUnix Makefiles" "/scratch/trilinos/workspace/trilinos-folder/SierraIntegrationCandidateTesting/Trilinos_parameter_experiment_sierra@2/Sierra_MPI_release_DEV_ETI_SERIAL-ON_OPENMP-OFF_PTHREAD-ON_CUDA-OFF_COMPLEX-ON/Trilinos"

**Comment by prwolfe** [comment]
Ouch - this is a painful work-around to a fragility that should not be present.  This means the basic mechanism for assembling these builds needs to follow a pattern that is not a standard cmake string or set of strings passed in from a command line.  Is this fragility in cmake itself or in the tribits processing that's creating all the sub-builds?

**Comment by bartlettroscoe** [comment]
> Ouch - this is a painful work-around to a fragility that should not be present. This means the basic mechanism for assembling these builds needs to follow a pattern that is not a standard cmake string or set of strings passed in from a command line. Is this fragility in cmake itself or in the tribits processing that's creating all the sub-builds?

I depends on how your look at things I guess.  In any case, this functionality in TriBITS would need to be refactored to avoid the problem with the spaces in strings.  But I honestly don't know how to do that.  The duality of spaces and array boundaries in CMake is a fundamental language flaw that I fight with every day that I do anything in CMake.

There are manage advantages to putting all of your configure settings in `*.cmake` files.  One of them is that it makes it easy for developers to reproduce your builds by just using `-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=<your-file>.cmake`.

That is my advise and I think it is the best approach after 9+ years of experience.

**Comment by bartlettroscoe** [comment]
@prwolfe,

How should we resolve this TriBITS issue?  We can either resolve it "wontfix" with the explained workaround or we can add the ability to specify the list of directories with comas `,` in addition to semi-colons `;` (then have TriBITS replace `,` with `;` before handing it to CMake).

Let me know which way you want to go.  I think it might be good to simply allow all cache var directory input lists that TriBITS handles to allow comas `,` instead of semi-colons `;` as a general way to resolve this issue.

**Comment by prwolfe** [comment]
I am going to close this as "wontfix" with the explained workaround.  It matches what we did the best I think.
