### ISSUE TITLE
gitdist:  Add Default Development Branch Support

### ISSUE THREAD

**Issue by jmgate** [TriBITSPub/TriBITS#235]
@bartlettroscoe, I had a realization while driving home today.  The reason we as applications wanted to stay on a `master`/`develop` workflow&mdash;the reason for all the git trickery of renaming `develop` to `real-develop` and then creating a new `develop` branch for the application&mdash;was coming at least in part from a desire to use `gitdist`.  For instance, if the application fork of Trilinos were to have the usual `master` and `develop` branches, and then a `app-dev` branch along the lines of what you showed for ROL, an app developer would have to do the following:
```bash
gitdist checkout develop
cd <trilinosLocation>
git checkout app-dev
gitdist checkout -b <featureBranch>
# do some work
```

and that little extra you need to do for Trilinos would be frustrating and easy to forget.

My earlier solution was all the git trickery in the application fork of Trilinos, but I realized we could solve the same problem in `gitdist` instead.  Suppose we add some way to configure `gitdist` such that you can specify the main development branch in all the repos you're using `gitdist` to manage.  I don't know if this would belong in the `.gitdist` file or elsewhere.  Then we could add a command to `gitdist` to check out that default branch in all repos.  For instance:
```bash
gitdist checkout-default-branch
gitdist checkout -b <featureBranch>
# do some work
```

Alternatively we may be able to do something along the lines of what you did with the repo version file, such that `gitdist checkout __DEFAULT_BRANCH__` would understand what you meant.  Actually I think I like this better, because we could also figure out how to `gitdist merge __DEFAULT_BRANCH__` or `gitdist rebase __DEFAULT_BRANCH__`, etc.

I can try to whip something up in the morning.

**Comment by bartlettroscoe** [comment]
@jmgate, let's meet tomorrow and talk about the EMPIRE workflow and how this might fit in.   We should go the EMPIRE workflows and as they relate to Trilinos.

**Comment by jmgate** [comment]
@bartlettroscoe, while I'm grateful we'll be able to use a `master`/`develop` workflow in EMPIRE's fork of Trilinos, this feature would still be useful for development as Drekar and Charon, for instance, aren't using `master`/`develop`.  For instance, when developing Trilinos, I now have the following `.gitdist` file:
```
. develop
DrekarBase master
EMPIRE develop
EMPIRE-DSMC develop
EMPIRE-Fluid develop
tcad-charon master
charon-data master
charon-ouo-data master
```

If it shouldn't make it into TriBITs, though, that's fine&mdash;I'll just keep it in my fork.

**Comment by bartlettroscoe** [comment]
@jmgate, okay, I can see the desire for this in various use cases.

But before we can merge this to the TriBITS 'master' branchs we need to add automated tests and documentation.  Can you look into doing this?

You can find automated tests for gitdist under TriBITS/test/python_utils/gitdist_UnitTests.py (see the ctest test in the CMakeLists.txt file).  And documentation should be added as another `--dist-help=<topic>` category explaining this.  If you can put that together, then I can review this.

**Comment by bartlettroscoe** [comment]
We might call this topic `--dist-help=default-branch`.

**Comment by jmgate** [comment]
I'll look into it&mdash;thanks @bartlettroscoe.

**Comment by jmgate** [comment]
Added the help topic&mdash;looking into unit testing now&hellip;

**Comment by jmgate** [comment]
@bartlettroscoe, this initial implementation is now documented (`--dist-help=default-branch`) and protected by a unit test (`test_dist_default_branch`, based off of `test_dot_gitdist`).

Do you suppose there's any need to support a `--default-branches=branch1,branch2,etc.` command line option, analogous to `--dist-repos=repo1,repo2,etc.`?  I doubt it, but if you'd like it for the sake of completeness, let me know.

**Comment by bartlettroscoe** [comment]
I don't think we would need a `--dist-default-branches` argument.  For more flexibility for things like this, we can just implement a special `dist-for-each` command (see  #135).

I will take a look.
