### ISSUE TITLE
No such file or directory: TribitsBuildReference.html

### ISSUE THREAD

**Issue by wfspotz** [TriBITSPub/TriBITS#242]
I am trying to upgrade the conda installer for Trilinos to release version 12.12.1. The build process downloads the 12.12.1 tarball and builds, gets almost to the end where it says it is "Fixing permissions", and fails with

    No such file or directory: '<INSTALL_DIR>/lib/cmake/tribits/doc/developers_guide/TribitsBuildReference.html'

I checked the file, and it is a symbolic link to `../build_ref/TribitsBuildReference.html`. I checked _that_ file, and it does not exist (although a couple of `TribitsBuildReference*.rst` files _do_ exist).

**Comment by bartlettroscoe** [comment]
@wfspotz, thanks for passing this along.  It looks like that symlink got committed by default.  I will remove the symlink from TriBITS and we can update the Trilinos 12.12 branch to not have this file.

**Comment by bartlettroscoe** [comment]
Actually, that file is not in TriBITS.  What likely happened is that that file just happened to be in the source TriBITS repo and it got copied over during the snapshot and then it did not get ignored in the target Trilinos git repo.  I will fix this and explain in those commits.

**Comment by wfspotz** [comment]
@bartlettroscoe OK, thanks for looking into this. Between now and the next update of the Trilinos 12.12 tarball, I will need to find a workaround. It looks to me like if, before my conda recipe does a `make install`, I can just delete the symbolic link

    cmake/tribits/doc/developers_guide/TribitsBuildReference.html

and I should be good.

**Comment by bartlettroscoe** [comment]
@wfspotz,

With the commit 9c8b47e that I just pushed to TriBITS, this type of error should not occur again.

Thanks again for the heads-up.

I will close this issue now.

**Comment by bartlettroscoe** [comment]
FYI:  I changed the snapshot-dir.py script to **not** clean the ignored files out of orig-dir by default after some thought.  I added as script to Trilinos to drive the snapshot with the new option `--clean-ignored-files-orig-dir` and updated the documentation for this at:

* http://trac.trilinos.org/wiki/TriBITSTrilinosDev#update_snapshot

Hopefully others using this script will do the same.
