### ISSUE TITLE
MPI_EXEC_MAX_NUMPROCS Configuration Problem

### ISSUE THREAD

**Issue by jmgate** [TriBITSPub/TriBITS#245]
Charon is running into the following configuration problem:  If we have a `CMakeLists.txt` file that has the code below,

```cmake
####################################################
# Run fem-dd
TRIBITS_ADD_ADVANCED_TEST(
  test_name

  TEST_0 EXEC charon_mp NOEXEPREFIX DIRECTORY ${PACKAGE_BINARY_DIR}/driver
    ARGS  --i=input.yaml --current
    NUM_MPI_PROCS 16
    PASS_REGULAR_EXPRESSION "Charon run completed."
    OUTPUT_FILE results.output

# epu the output
  TEST_1  EXEC ${SEACAS_BINARY_DIR}/applications/epu/epu NOEXEPREFIX NOEXESUFFIX
    ARGS  "-auto" "results.exo.16."
    NUM_MPI_PROCS 1

# Check exodiff
  TEST_2 EXEC ${SEACAS_BINARY_DIR}/applications/exodiff/exodiff NOEXEPREFIX NOEXESUFFIX
    ARGS -f input.exodiff results.exo results.gold.exo
  )
SET_PROPERTY(TEST Charon_test_name PROPERTY LABELS test_name heavy)
```

and if `MPI_EXEC_MAX_NUMRPOCS` is less than 16 (because `MPI_EXEC_MAX_NUMPROCS_DEFAULT` is less than 16), `TRIBITS_ADD_ADVANCED_TEST()` doesn't add this test because it requires more processors than we're allowed to use.  However, when CMake hits the `SET_PROPERTY()` line at the bottom, it tries to set a property for a test that hasn't been created yet, and the configuration fails.

Is this a bug in TriBITS, or a problem with how our `CMakeLists.txt` files are written?  Is there some TriBITS equivalent to `SET_PROPERTY()`?  I couldn't find one, but perhaps I wasn't looking in the right place.

**Comment by bartlettroscoe** [comment]
@jmgate,

Take a look at the argument `ADDED_TEST_NAME_OUT <testName>` at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#overall-arguments-tribits-add-advanced-test

You use it like:

```
TRIBITS_ADD_ADVANCED_TEST(
  test_name
  ...
  ADDED_TEST_NAME_OUT test_name_NAME
  )
IF (test_name_NAME)
  SET_PROPERTY(TEST ${test_name_NAME} PROPERTY LABELS test_name heavy)
ENDIF()
```

That solves two problems:
* Automatically returns the right test name
* Determines if the test got added or not based on the various criteria for if a test can be excluded

Please let me know if that does not solve this problem.

P.S. TriBITS will soon add official support for test labels after upgrading for CMake 3.10 (now that CTest can differentiate labels used for subprojects from labels used for other purposes).

**Comment by jmgate** [comment]
Thanks @bartlettroscoe&mdash;closing&hellip;
