### ISSUE TITLE
It doesn't install all needed files?

### ISSUE THREAD

**Issue by yurivict** [TriBITSPub/TriBITS#253]
While trying to create the FreeBSD port, I'm seeing that it installs only these files:
```
include/Makefile.export.TriBITS
include/TriBITS_version.h
lib/cmake/TriBITS/TriBITSConfigVersion.cmake
```

It seems like there should be more files. What could be wrong?

**Comment by bartlettroscoe** [comment]
What is the context for usage here?  Just curious.

Note that what should happen in an "install" of TriBITS separate from its git repo has not really been defined yet.  See #52 and #114.  The big issue there is how to handle versioning and how to announce that in the TriBITS install. 

Up until now, all customers of TriBITS have used a staged integration (or almost continuous integration) with TriBITS and have typically either maintained their own clone of TriBITS or snapshotted TriBITS into their git repo, both of which track version info.  See:

* https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-directory-snapshotting

But supporting standard versioned releases and better handling of backward compatibility will be needed to support a larger user base for the code.

**Comment by bartlettroscoe** [comment]
No response to my comment [above](https://github.com/TriBITSPub/TriBITS/issues/253#issuecomment-372185033) 10 months ago so closing.
