### ISSUE TITLE
HOW CAN I SOLVE THIE PROBLEM,THANKS

### ISSUE THREAD

**Issue by gavinjou818** [TriBITSPub/TriBITS#254]
![_062](https://user-images.githubusercontent.com/17568341/37657738-c6475654-2c86-11e8-807d-d81aa1e9976b.png)

**Comment by bartlettroscoe** [comment]
@gavinjou818, can you please provide some details about your system, CMake version, Python version and other info so that I have a shot at reproducing the problem?  You can also provide this info by doing:

```
make dashboard
```

That will post to the TriBItS CDash site and then I can see some of this stuff myself.

**Comment by gavinjou818** [comment]
This is my system's imformation
![_064](https://user-images.githubusercontent.com/17568341/37664497-6bdabd7c-2c96-11e8-8cf9-6830f45e0f6c.png)
I also tried with py2.7.13,but it didn`t work. So i have confused.

**Comment by bartlettroscoe** [comment]
That is a reasonable system.  Can you run:

```
$ ctest -VV -R "(TriBITS_TribitsExampleProject_ALL_ST_NoFortran|TriBITS_CheckinTest_UnitTests)" &> ctest.txt
```

and then attach the file `ctest.txt` file?

That will tell me what is actually failing.

**Comment by bartlettroscoe** [comment]
@gavinjou818, this looks to be an internationalization problem assuming tools returning English text.

For example,  the below test is Expecting output from `diff` for example but instead diff is outputting:

```
169: TEST_9
169: 
169: Make sure right directoires are excluced
169: 
169: Running: "diff" "-qr" "/home/gavinjou/TriBITS/tribits/examples/TribitsExampleProject" "tribitsexproj-1.1-Source"
169: 
169:   Running in working directory "/home/gavinjou/TriBITSBUILD/test/core/ExamplesUnitTests/TriBITS_TribitsExampleProject_ALL_ST_NoFortran"
169: 
169: --------------------------------------------------------------------------------
169: 
169: 只在 /home/gavinjou/TriBITS/tribits/examples/TribitsExampleProject/cmake 存在：ctest
169: 只在 /home/gavinjou/TriBITS/tribits/examples/TribitsExampleProject 存在：.gitignore
169: 只在 /home/gavinjou/TriBITS/tribits/examples/TribitsExampleProject/packages 存在：mixed_lang
169: 只在 /home/gavinjou/TriBITS/tribits/examples/TribitsExampleProject/packages 存在：wrap_external
169: 
169: --------------------------------------------------------------------------------
169: 
169: TEST_9: Return code = 1
169: TEST_9: Pass criteria = Match REGEX {Only in .*/TribitsExampleProject/cmake: ctest} [FAILED]
169: TEST_9: Pass criteria = Match REGEX {Only in .*/TribitsExampleProject: .gitignore} [FAILED]
169: TEST_9: Pass criteria = Match REGEX {Only in .*/TribitsExampleProject/packages: mixed_lang} [FAILED]
169: TEST_9: Pass criteria = Match REGEX {Only in .*/TribitsExampleProject/packages: wrap_external} [FAILED]
169: TEST_9: Result = FAILED
```

I suspect there may be something similar going on with the TriBITS_CheckinTest_UnitTests (but I would have to reproduce for myself to see the details for why it failed).

I don't think these failures don't represent problems with the TriBITS software, only with the tests assuming tools returning standard English output.  It may be pretty hard to keep these tests very strong and also make them work for all languages.  It is likely better to just exclude these tests when it detects a non-English env (but I am not sure how to do that).  Any suggestions of a portable way to do this?

**Comment by gavinjou818** [comment]
I'm sorry , i have no idea how to be compatible with different language env,i try to change my system to english env and rebuild this project again..  Thanks for your help..

**Comment by gavinjou818** [comment]
![selection_001](https://user-images.githubusercontent.com/17568341/37670663-d21f2394-2ca4-11e8-9477-01b475e46a92.png)
oh!!  it works.. .. you're right..

**Comment by bartlettroscoe** [comment]
@gavinjou818, glad this is working for you now.  Closing as complete.
