### ISSUE TITLE
TriBITS does not pass along "0" in ARGS of TRIBITS_ADD_TEST

### ISSUE THREAD

**Issue by kddevin** [TriBITSPub/TriBITS#265]
The following CMakeLists.txt code works correctly

> TRIBITS_ADD_TEST(
>   waterman_mpi
>   NAME waterman_mpi_with_comm_duplicate
>   ARGS "1"
>   COMM mpi
> )

It generates a command line with "1" as an argument:

> Command: "/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.10.1/bin/mpiexec" "-np" "4" "/home/kddevin/tmp/tmp/Trilinos/Obj_zoltan2/packages/zoltan2/test/temp/Zoltan2_waterman_mpi.exe" "1"

But when ARGS is changed to "0"

> TRIBITS_ADD_TEST(
>   waterman_mpi
>   NAME waterman_mpi_without_comm_duplicate
>   ARGS "0"
>   COMM mpi
> )

TriBITS does not put "0" on the command line

> Command: "/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.10.1/bin/mpiexec" "-np" "4" "/home/kddevin/tmp/tmp/Trilinos/Obj_zoltan2/packages/zoltan2/test/temp/Zoltan2_waterman_mpi.exe"

The value given in ARGS should not matter; whatever is provided in ARGS should be on the generated command line.

**Comment by kddevin** [comment]
It appears if ARGS is "N", the "N" is not passed along either.


> TRIBITS_ADD_TEST(
>   waterman_teuchoscomm
>   NAME waterman_teuchoscomm_without_comm_duplicate
>   ARGS "N"
>   COMM mpi serial
>   PASS_REGULAR_EXPRESSION "PASS"
> )


> 10/13 Testing: Zoltan2_waterman_teuchoscomm_without_comm_duplicate_MPI_4
> 10/13 Test: Zoltan2_waterman_teuchoscomm_without_comm_duplicate_MPI_4
> Command: "/projects/sems/install/rhel6-x86_64/sems/compiler/gcc/4.9.3/openmpi/1.10.1/bin/mpiexec" "-np" "4" "/home/kddevin/tmp/tmp/Trilinos/Obj_zoltan2/packages/zoltan2/test/temp/Zoltan2_waterman_teuchoscomm.exe"

**Comment by kddevin** [comment]
Changing "N" or "0" to "X" works as expected.

**Comment by bartlettroscoe** [comment]
@kddevin, that is strange behavior.  I need to add an automated test to try to expose this defect and then see if it can be fixed.

Is it urgent to fix this ASAP or do you have a workaround in place?

**Comment by kddevin** [comment]
No rush; I worked around it.  teuchos/comm/test/Comm/CMakeLists.txt has examples (see tests for waterman_mpi_without_comm_duplicate and waterman_teuchoscomm_without_comm_duplicate).  The ARGS with "X" should really be ARGS with "N" but Tribits didn't add  "N" to the command line.  Thanks.

**Comment by bartlettroscoe** [comment]
@kddevin, I have reproduced this with some unit tests in TriBITS.  I will fix and update the TriBITS snapshot in Trilinos.
