### ISSUE TITLE
Missing Version.cmake File Yields `<libname>.so.SOVERSION` Files

### ISSUE THREAD

**Issue by jmgate** [TriBITSPub/TriBITS#270]
Not sure if this is a bug or intended behavior.  Charon recently overhauled its repositories and the way they build together.  Now Trilinos builds as part of Charon instead of the other way around.  When putting together the new Charon meta-repository I left out the `Version.cmake` file because the documentation indicated it was optional.  Apparently when you do so and then build with shared libraries, you wind up generating `<libname>.so.SOVERSION` shared objects.  If that's intended behavior, that's fine&mdash;feel free to close.  If it's not, you might want to protect [this line](https://github.com/TriBITSPub/TriBITS/blob/adbf3c11f154d5b308fcc7e0188588892de6c488/tribits/core/package_arch/TribitsLibraryMacros.cmake#L841) with an `IF()`.  If this is a bug, there's no rush on our end for fixing it&mdash;we just added a `Version.cmake` file and now all is well.

**Comment by bartlettroscoe** [comment]
@jmgate, this should be fixed in commit d4bf3e3 I just pushed to 'master'.  Do you need to TriBITS snapshotted to Trilinos 'develop'?  If not, it will be updated soon anyway.

**Comment by jmgate** [comment]
It can wait. Thanks for the quick turnaround.

On Jan 17, 2019, at 4:15 PM, Roscoe A. Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


@jmgate<https://github.com/jmgate>, this should be fixed in commit d4bf3e3<https://github.com/TriBITSPub/TriBITS/commit/d4bf3e395df7d831dfb96e01e13fda3f778da1d5> I just pushed to 'master'. Do you need to TriBITS snapshotted to Trilinos 'develop'? If not, it will be updated soon anyway.

**Comment by bartlettroscoe** [comment]
Actually, I am going to go ahead and close this because I am pretty sure about the fix and the automated tests for the fix.
