### ISSUE TITLE
Change WARNING to INFO when extra repos don't exist

### ISSUE THREAD

**Issue by glhenni** [TriBITSPub/TriBITS#271]
In the charon project we have some rather large data files used for nightly tests. We recently segregated these into different repositories, in part, to allow us to avoid having to clone them unless we really need them. The trouble is that now we get messages such as:

```WARNING: Ignoring missing extra repo 'heavyTests' as requested since /home/glhenni/Nightly-Testing/Charon2/tcad-charon/test/heavyTests does not exist```

This is problematic for us because cmake/ctest/cdash does a simple search for words like "WARNING" during the configure and if it finds them it highlights them as such in CDash. 

I would argue that since the developer has already specified **\<Project\>_IGNORE_MISSING_EXTRA_REPOSITORIES=ON** that issuing a warning about it is incorrect behavior. I would think, at most, perhaps an info message would be warranted. 

@jmgate should also be aware of this behavior.

**Comment by bartlettroscoe** [comment]
@glhenni and @jmgate, sure, we can remove the usage of `WARNING`.  Are you okay with `NOTE:` instead of `INFO`?  I think there is other output that says `NOTE`.

**Comment by jmgate** [comment]
Fine with me.

On Jan 17, 2019, at 9:42 PM, Roscoe A. Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


@glhenni<https://github.com/glhenni> and @jmgate<https://github.com/jmgate>, sure, we can remove the usage of WARNING. Are you okay with NOTE: instead of INFO? I think there is other output that says NOTE.

**Comment by glhenni** [comment]
Yes, NOTE is just as good. Thanks.

On Jan 18, 2019 05:37, "Jason M. Gates" <notifications@github.com> wrote:
Fine with me.

On Jan 17, 2019, at 9:42 PM, Roscoe A. Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


@glhenni<https://github.com/glhenni> and @jmgate<https://github.com/jmgate>, sure, we can remove the usage of WARNING. Are you okay with NOTE: instead of INFO? I think there is other output that says NOTE.

**Comment by bartlettroscoe** [comment]
With the push of the commit de606e5c5adfdff290df02c2e9137539300e9999 to TriBITS GitHub 'master' and the merge of TriBITS snapshot to Trilinos in Trilinos PR https://github.com/trilinos/Trilinos/pull/4218 to Trilinos 'develop', this should not be resolved.

I will now put this issue "in review" and wait for confirmation from @jmgate and @glhenni that CDash no longer reports these warnings.

**Comment by jmgate** [comment]
I'm seeing these `WARNING`s now as `NOTE`s in my local build.  @glhenni, you'll have to update whatever TriBITS clone our nightly builds are pointing to, and then we should be good.

**Comment by glhenni** [comment]
CDash reported all clear on all the jobs that update TriBITS automatically so we're good to go. Thanks Ross!

**Comment by bartlettroscoe** [comment]
@glhenni said:

> CDash reported all clear on all the jobs that update TriBITS automatically so we're good to go. Thanks Ross!

Excellent!  Closing as complete.
