### ISSUE TITLE
Add RawAndTribitsHelloWorld example project and howto

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#276]
We need a TriBITS example and howto for putting a TriBITS build system and a raw CMake build system side-by-side.  This was requested by a Trilinos developer but this is something that everyone should know how to do.

**Comment by bartlettroscoe** [comment]
@csiefer2,

The long-promised and howto and example for putting a raw CMake build system and a TriBITS build system side-by-side is pushed to TriBITS shown at:

* https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-put-a-tribits-and-raw-cmake-build-system-side-by-side

and:

* https://github.com/TriBITSPub/TriBITS/tree/master/tribits/examples/RawAndTribitsHelloWorld

If you clone the TriBITS repo, you can test this out yourself as described the above howto and in the README:

* https://github.com/TriBITSPub/TriBITS/blob/master/tribits/examples/RawAndTribitsHelloWorld/README

Please let me know if this is not clear and I will try to improve it to address your questions.

Sorry for the very long delay in getting this done.

**Comment by bartlettroscoe** [comment]
@csiefer2,

Ever have a chance to look at this?  Still looking for a review before I close this issue.

**Comment by csiefer2** [comment]
I can now make cmake segfault :)

**Comment by bartlettroscoe** [comment]
@csiefer2 said:

> Evidently my tribits_add_library() call inside my child directory's CmakeLists.tribits.cmake causes cmake to woof.

Any chance you accidentally have a recursive file include or something?  That can cause CMake to crash.

**Comment by csiefer2** [comment]
I don't think so.

**Comment by bartlettroscoe** [comment]
@csiefer2, can we close this?  Are you good to go with this?

**Comment by bartlettroscoe** [comment]
@csiefer2 reported to me in person a few months ago that this looked good for him.

Closing as complete.
