### ISSUE TITLE
Shorten file names in TriBITS to avoid problems cloning on Windows

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#297]
It is reported in https://github.com/kokkos/kokkos-kernels/issues/395#issuecomment-555740112 that TriBITS now has some long file names like:

```
test/ci_support/cdash_analyze_and_report/raw_cdash_data_twoif_12_twif_9/test_history/2018-10-28-mutrino-Trilinos-atdm-mutrino-intel-opt-openmp-KNL-Intrepid2_unit-test_Discretization_Basis_HCURL_TRI_In_FEM_Serial_Test_01_SLFadDouble_MPI_1-HIST-30.json
```

This issue will be to find a way to reduce these file names and still be able to run these important automated tests.

**Comment by sethrj** [comment]
Thanks @bartlettroscoe !

**Comment by bartlettroscoe** [comment]
I downloaded a Git GUI for Windows, generated a new SSH key in the tool, submitted that to my set of SSH keys on github.com and I was able to clone from `git@github.com:TriBITSPub/TriBITS.git` and I was able to reproduce the checkout (not clone) error for the file

`test/ci_support/cdash_analyze_and_report/raw_cdash_data_twoif_12_twif_9/test_history/2018-10-28-mutrino-Trilinos-atdm-mutrino-intel-opt-openmp-KNL-Intrepid2_unit-test_Discretization_Basis_HCURL_TRI_In_FEM_Serial_Test_01_SLFadDouble_MPI_1-HIST-30.json`

I will work to shorten these file names and I should be able to confirm that the problem is fixed.

**Comment by bartlettroscoe** [comment]
From:

* https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

I appears that you might be able to solve this problem by setting:

```
git config --system core.longpaths true
```

But if that does not work, it looks like I have something that works.  (I had to shorten just that one long filename and make another directory shorter and the native Windows git clone appears to work.)

**Comment by bartlettroscoe** [comment]
@sethrj, looks like as of commit ddd1d9d I just pushed to 'master', this should be fixed.  Before the fix, the clone crashed with that error message.  After the fix, the clone passes 100% and completes the checkout of 'master'.

Can you please confirm?

**Comment by sethrj** [comment]
It works! Thanks!

**Comment by bartlettroscoe** [comment]
> It works! Thanks!

Great!  Closing as complete.
