### ISSUE TITLE
snapshot-dir.py:  Add --exclude Option

### ISSUE THREAD

**Issue by jmgate** [TriBITSPub/TriBITS#307]
Part of #48.

I'd like `snapshot-dir.py` to have the ability to exclude files or directories when snapshotting.  As part of [compadre#164](https://github.com/SNLComputation/compadre/issues/164), I want to be able to snapshot part of Compadre into Trilinos, but I want to exclude certain directories and files.  I could write my own wrapper script in Compadre ([compadre#175](https://github.com/SNLComputation/compadre/issues/175)), but I'd prefer if the core functionality lived in `snapshot-dir.py` itself.

@bartlettroscoe, I'll start hacking away at this.  If there are particular design considerations you have in mind, please let me know.

**Comment by jmgate** [comment]
@bartlettroscoe, would you like to be able to `--exclude file1 file2 dir1 dir2`, or would you prefer to have separate `--exclude` and `--exclude-dir` options?

**Comment by jmgate** [comment]
And do you mind if I swap out `optparse` for `argparse`?  If we stick with `optparse`, which is deprecated, we'd have to do `--exclude file1 --exclude file2 --exclude dir1 --exclude dir2`, which I wouldn't prefer.  If swapping out is okay, should I do that in a separate PR?

**Comment by bartlettroscoe** [comment]
> And do you mind if I swap out optparse for argparse? 

@jmgate, I think that means that we loose support for Python 2.6, right and RHEL6?  The `argparse` module was only added in Python 2.7:

* https://pymotw.com/2/argparse/

Are we giving up on supporting RHEL6 systems at this point?  Otherwise, I guess SEMS has a Python 2.7 module so I suspect that is okay.   The cdash_analyze_and_report.py tool requires Python 2.7 so I guess that is okay.

**Comment by bartlettroscoe** [comment]
> would you like to be able to `--exclude file1 file2 dir1 dir2`, or would you prefer to have separate `--exclude` and `--exclude-dir` options?

@jmgate, whatever makes the most sense to you.  Note that adding support for excludes has been on the todo list for a while as shown [here](https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#heading=h.pff7uxigbp71).

Thanks for working on this.
