### ISSUE TITLE
Make all TriBITS Python code compatible with Python 2.7 and Python 3.x

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#309]
Python 2.x is officially unsupported by the Python community as of Jan 1 2020 (see https://python3statement.org/).  Many developers and users have transitioned to Python 3.x and have default environments where only Python 3.x is installed.  Therefore, TriBITS Python software should work with Python 3.x (versions TBD).

However, Python 2.7 is the default Python version installed on RedHat 7 systems, which is the dominate OS at SNL.  As a result, it you want your software to be easily used by everyone, you need to keep supporting Python 2.7 for as long as RedHat 7 systems are still dominate (like they currently are at SNL).

This story is to once and for all update TriBITS Python software to support Python 2.x and set up automated testing of TriBITS Python 2.7 and Python 3.x and ensure that all TriBITS python software works with both going forward.

**TASKS:**

* Select a target version of Python 3.x to use for TriBITS testing ...
* Get all of TriBITS test suite to pass with both Python 2.7 plus Python 3.x (version TBD) ...
* Update Travis CI testing to test with both Python  2.7 and Python 3.x (versions TBD) ...

**Comment by bartlettroscoe** [comment]
@jmgate, what is the oldest version of Python 3.x that we should be testing against going forward?  Assuming that Python 3.x releases are backwards compatible, that will determine what we can use from the Python 3.x language and the standard modules.

**Comment by bartlettroscoe** [comment]
It appears there is no standard yum package to install Python 3 on RHEL7:

* https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/

What a mess.

**Comment by jmgate** [comment]
I'd prefer going with at least Python 3.6 such that we can make use of [Literal String Interpolation](https://www.python.org/dev/peps/pep-0498/).  There's a [good write-up of the new formatting style](https://realpython.com/python-f-strings/) over at RealPython.

**Comment by jmgate** [comment]
@bartlettroscoe, do you have an idea on how long it would take to get this conversion done?  Compadre only supports Python 3.6 and above, so when trying to use `SnapshotDir.py` in a wrapper script to snapshot Compadre into Trilinos, we run into the usual 2/3 bytes-to-string conversion issues.

Instead of importing `SnapshotDir` and then using it directly, I could fire off a subprocess to call `python2 snapshot-dir.py`, but that doesn't feel right.

**Comment by bartlettroscoe** [comment]
@jmgate, it should not be too hard to get SnapshotDir.py to work with Python 3.  There is not a lot of code there.

**Comment by jmgate** [comment]
Do you have time to deal with it this week, or shall I take a crack at it?

**Comment by bartlettroscoe** [comment]
> Do you have time to deal with it this week, or shall I take a crack at it?

@jmgate, if you have time to take a crack at this, I would be greatly appreciative :-) 

Hopefully this would not be too hard given that most of the rest of the python code in TriBITS was ported to Python3 in the past.

**Comment by jmgate** [comment]
I'll take a crack at it.  I have an idea of what's required based on what was done for `gitdist` a while ago.

**Comment by bartlettroscoe** [comment]
CC: @jmgate

FYI: I finally did this for all of TriBITS.  This was motivated by trilinos/Trilinos#7376 which required some TriBITS python code to work with Python 3.6 used by some of the Trilinos PR builds.  Therefore, I just decided to bite the bullet and port of of TriBITS to work with Python 3.x but keep Python 2.7 compatibility for now.  I tested this with Python 3.5.2 and Python 2.7.5 (the default with RHEL-7).

**Comment by bartlettroscoe** [comment]
With PR #343 merged to 'master' (but still needing a review), I am putting this in review.

@jmgate, if you want or review, please due so in #343.  Otherwise, I will snapshot to Trilinos.

**Comment by bartlettroscoe** [comment]
I am going to call this done with the merge of PR #344.

**Comment by cgcgcg** [comment]
@bartlettroscoe How about the dashboard_driver? For example, this looks like it's gonna lead to issues with Python3.
https://github.com/TriBITSPub/TriBITS/blob/c8abb338d90d9f4065cd415eca01c7212a754084/tribits/dashboard_driver/tdd_driver.py#L204-L206

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe How about the dashboard_driver?

@cgcgcg, the TriBITS dashboard_driver was created by a contractor years ago while TriBITS was still a part of Trilinos and was never put under automated testing.  I stopped using it years ago. (They were way behind schedule and way over budget so automated testing never happened.  This was another hard lesson about having contractors writing software that is handed over to you to maintain.)
