### ISSUE TITLE
HDF5: how to set HDF5_PREFER_PARALLEL option?

### ISSUE THREAD

**Issue by mayrmt** [TriBITSPub/TriBITS#312]
I have set `-D TPL_ENABLE_HDF5:BOOL=ON` in my `cmake` configure line. `FindHDF5()` finds an HDF5 installation, but (as documented in the `FindHDF5()` documentation, the serial version is preferred over the parallel. Furthermore, one can set the option `HDF5_PREFER_PARALLEL` to flip this behavior.

I'd like to tell `FindHDF5()` to prefer the parallel version. How can I specify this on the `cmake` command line? Or on a more general note, how can I define CMake options to be passed to `Find<AnyPackage>()`?

**Comment by bartlettroscoe** [comment]
@mayrmt, I am not sure the full history of the tribits/common_tpls/FindTPLHDF5.cmake module but you can see how it is specified in:

* https://github.com/TriBITSPub/TriBITS/blob/master/tribits/common_tpls/FindTPLHDF5.cmake

Can you just set `-DHDF5_PREFER_PARALLEL=ON` when you configure Trilinos?  Does that work?

**Comment by bartlettroscoe** [comment]
It looks like applying the PR #128 would change the default to find a parallel HDF5 when MPI is enabled.  But this will break backward comparability (which is likely why I did not apply this at the time).  But this is a good time to break Trilinos backward compatibility with Trilinos 13.0 coming up soon.

Would it be helpful to just apply PR #128 and update the version of TriBITS in Trilinos?  Or is it sufficient to set `-DHDF5_PREFER_PARALLEL=ON` when you configure Trilinos?

**Comment by mayrmt** [comment]
@bartlettroscoe Thanks for your ideas! I configured Trilinos with `-DHDF5_PREFER_PARALLEL=ON` and it found the `openmpi` version of HDF5. Build and installation also worked just fine, also linking my app against this Trilinos installation work as well. (I had some prior trouble due to serial HDF5 in Trilinos, but parallel HDF5 in the application code). 

Summary: setting `-DHDF5_PREFER_PARALLEL=ON` answers my question, so I will close this issue. 

Yet, I think that merging PR #128 makes sense. For example, Trilinos checks for parallel HDF5 in case that MPI is enabled, so PR #128 would help to satisfy this requirement without additional user interaction.

**Comment by bartlettroscoe** [comment]
> Trilinos checks for parallel HDF5 in case that MPI is enabled,

@mayrmt, thanks for pointing that out.  I had not realized that.  I have merged #128.
