### ISSUE TITLE
TRIBITS_CTEST_DRIVER(): Add support for build-only builds with no running tests

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#317]
## Description

There are cases where one wants to be able to just configure and build a project with `TRIBITS_CTEST_DRIVER()` and submit to CDash but does not want to actually run any tests.  The reason to not run tests are:

* It can be difficult to get setup to run the tests robustly on a given machine.
* It can take a long time to run tests and we can't afford that given the CPU budget for all of our builds.
* We may only want to build the libraries and install and report the success/failure of that in CDash

There are several driver use cases for this but the main ones are related to the ATDM Trilinos builds (e.g. see [ATDV-183](https://sems-atlassian-srn.sandia.gov/browse/ATDV-183) and [ATDV-271](https://sems-atlassian-srn.sandia.gov/browse/ATDV-271)).

Now, the `TRIBITS_CTEST_DRIVER()` function accepts the option `CTEST_DO_TEST` which can be set to `OFF`.  However, that will result in no test results being submitted to CDsah and the tool `cdash_analyze_and_report.py` will think that the build has missing test results.  Therefore, we want to just not call `add_test()` internally  so that running the tests with `ctest_test()` will result in zero tests run and will submit test results showing zero tests run.  That will tell `cdash_analyze_and_report.py` that we purposefully did not want to run any tests and therefore it will not report missing test results.

## Requirements / Use Cases:

* Skip all add_test(): Skip adding all tests with add_test() globally for all tests/examples in all packages.

* Black-list package tests: Add tests with add_test() for all packages that have tests/examples enabled but don't add_test() for a listed subset of packages.

* White-list package tests: Skip adding tests with add_test() for all packages except for a white-list of packages to allow add_test().

* Build (and install) libraries only: Don't enable the building of any tests or examples to avoid the expense of building them.

* Build libraries (and install) and test/example binaries:  Build everything just as you would before but don't define any tests by calling `add_test()`.

## Implementation ideas

To address the use case of only building libraries, some tweaks will need to be made the `TRIBITS_CTEST_DRIVER()`.  The current outer enable/disable logic determines what packages to test based on what tests get enabled in packages.  Therefore, we can't set `<Project>_ENABLE_TEST=OFF` in the outer enable/disable logic or no packages will get enabled in the inner configure and build.

To address setting `<Project>_ENABLE_TEST=OFF` only in the inner configure, we could add the `TRIBITS_CTEST_DRIVER()` option:

* `<Project>_INNER_ENABLE_TESTS`:  If set to `OFF`, then `<Project>_ENABLE_TESTS` would be set to `OFF` in the inner configure.  Currently, this is hard-coded to `ON` and the default would stay `ON`.

So setting the option `<Project>_INNER_ENABLE_TESTS=OFF` in the outer ctest -S script takes care of not building the inner test/example executables and should also avoid the definition of any tests that would get defined using `add_test()`.  Therefore, this should handle the libs-only build and install use case above.

The other use case is when we want to build all of the inner test/example executables but we just don't want to call `add_test()` to add them as CTest tests.  For that, we could start by defining the following basic TriBITS Core project options:

* `<Package>_SKIP_CTEST_ADD_TEST=[ON|OFF]`:  If set to `ON`, then `TRIBTS_ADD[_ADVANCED]_TEST()` would not result in `add_test()` getting called for the given package.  The default value would be given by `${<Project>_SKIP_CTEST_ADD_TEST}`.

* `<Project>_SKIP_CTEST_ADD_TEST=[ON|OFF]`: Sets the default value for `<Package>_SKIP_CTEST_ADD_TEST`.  The default would be `OFF` (or any tests defined would be added).

When tests for a given packages are not added in this way, we should print `SkipAddTests` in the `Processing package: <Package> (..., SkipAddTests)` line and not sound-off in every test that would have otherwise been added.

So the options `<Package>_SKIP_CTEST_ADD_TEST` and `<Project>_SKIP_CTEST_ADD_TEST` would get handled in TriBITS Core proper and would need unit tests for that.

To support this in the outer `TRIBITS_CTEST_DRIVER()`, we would add the option `<Package>_SKIP_CTEST_ADD_TEST` as well there and it would pass that option down to the inner configure, and that is all.

So the option `<Package>_SKIP_CTEST_ADD_TEST=ON` in the outer ctest -S script would take care of the use case were we want to build the test/example executables but we don't want to run any tests.

**Comment by bartlettroscoe** [comment]
Note, another way to avoid running tests would be to pass in `INCLUDE_LABEL DO_NOT_MATCH_ANY_LABELS` to `ctest_test()`.  That would not match any exiting labels (hopefully) but that seems like a hack and it would be really confusing if someone did define the label `DO_NOT_MATCH_ANY_LABELS`.  Let's not do hacks.

And even for just directly interacting with the project itself doing your development it could be useful to support the use cases:

* Black-list package tests: Add tests with add_test() for all packages that have tests/examples enabled but don't add_test() for a listed subset of packages.
  * `-D<Project>_ENABLE_TESTS=ON -D<Package1>_SKIP_CTEST_ADD_TEST=ON ... -D<PackageN>_SKIP_CTEST_ADD_TEST=ON `

* White-list package tests: Skip adding tests with add_test() for all packages except for a white-list of packages to allow add_test().
  * `-D<Project>_ENABLE_TESTS=ON -D<Project>_SKIP_CTEST_ADD_TEST=ON -D<Package1>_SKIP_CTEST_ADD_TEST=OFF ... -D<Project>_SKIP_CTEST_ADD_TEST=OFF`

**Comment by bartlettroscoe** [comment]
@e10harvey,

If you have some time, would you be willing to review the above spec for this Issue and be willing to look at the PR that implements this?

**Comment by e10harvey** [comment]
> @e10harvey,
> 
> If you have some time, would you be willing to review the above spec for this Issue and be willing to look at the PR that implements this?

@bartlettroscoe: Certainly. I'll try to get back to you tomorrow afternoon.

**Comment by bartlettroscoe** [comment]
This has been done for a long time and is working great.   We use this for several of the ATDM Trilinos builds currently.
