### ISSUE TITLE
Enable printing of product-specific citation information to TriBITS

### ISSUE THREAD

**Issue by maherou** [TriBITSPub/TriBITS#320]
In my experience, citation of software is typically done far less often that it should be.  One approach that might help is to have a final message printed at the end of a TriBITS build that tells the installer how the built software should be cited.  

I think a text block variable defined by the TriBITS client could be a way to allow TriBITS to support its users.  TriBITS itself could also print such a message.

As an example, TriBITS could allow Trilinos to define a text block and then print it at the very end of a successful build.  Something like this would work:

```
If you publish a paper based on results from Trilinos, please cite us: https://trilinos.github.io/cite.html
Thank you.
```

**Comment by bartlettroscoe** [comment]
@maherou would this be on a package-by-package basis or just at the very end of the Trilinos configure and/or build process?

**Comment by maherou** [comment]
I think it is best to have it just at the end. Otherwise it will just get lost in the stream of text.  The https://trilinos.github.io/cite.html has instructions for citing a specific package.

**Comment by bartlettroscoe** [comment]
@maherou, I don't know how to get CMake to print some message at the end of the default 'all' target during the build.  But it is trivial to print something at the end of the configure stage.

By why would people not just get citation info from the Trilinos/README.md file?  Is the idea to make it easy for an automated tool like in Spack to scrape this info from the build output?

**Comment by maherou** [comment]
Printing at the end of configure would be good.  Basically, my thought is that it would be good to print a reminder to the user that they should cite the software they are using.  

Someone can certainly get this information if they go looking for it, but that has always been the case and yet we still don’t get all of our users citing our software.  I was thinking this kind of message would be a polite reminder they will see whenever they run configure.

**Comment by bartlettroscoe** [comment]
Then a `message()` statement should go a the very bottom of `Trilinos/CMakeLists.txt`.

**Comment by maherou** [comment]
So, it looks like we can get by with just changing the existing Trilinos CMakeLists.txt file without a new TriBITS feature by adding something like:


message(STATUS "If publishing results using Trilinos, please cite us: https://trilinos.github.io/cite.html")

Correct?

If so, please feel free to close this issue and I will add an issue to the Trilinos database.

Thanks.

Mike

On May 24, 2020, at 9:57 AM, Roscoe A. Bartlett <notifications@github.com> wrote:

﻿

Then a message() statement should go a the very bottom of Trilinos/CMakeLists.txt.

**Comment by bartlettroscoe** [comment]
> So, it looks like we can get by with just changing the existing Trilinos CMakeLists.txt file without a new TriBITS feature ...

@maherou, correct. 

I am trying to trim down TriBITS to just the essential for compatible package and projects or significant functionality can be leveraged across many projects.

**Comment by maherou** [comment]
I transferred this discussion to Trilinos: https://github.com/trilinos/Trilinos/issues/7423

Closing this issue.
