### ISSUE TITLE
CMAKE_BUILD_TYPE tests use STREQUAL -- Case Sensitive

### ISSUE THREAD

**Issue by gsjaardema** [TriBITSPub/TriBITS#325]
The tests on `CMAKE_BUILD_TYPE` typically use a `STREQUAL` comparison which is case-sensitive.  Therefore, the Project settings for `ENABLE_DEBUG` and `ENABLE_DEBUG_SYMBOLS` are only set to true if the build type is 'DEBUG' and not 'Debug'.  However, the help string for `CMAKE_BUILD_TYPE` shows `Debug` as a valid entry.
```
//Choose the type of build, options are: None Debug Release RelWithDebInfo
// MinSizeRel ...
```
Below is the differences in the CMakeCache.txt if `CMAKE_BUILD_TYPE` is set to `DEBUG` and `Debug`
```
ews01143:build(master)> diff CMakeCache.txt CMakeCache.txt.save
88c88
< CMAKE_BUILD_TYPE:STRING=DEBUG
---
> CMAKE_BUILD_TYPE:STRING=Debug
1031c1031
< SEACASProj_ENABLE_CONFIGURE_DEBUG:BOOL=ON
---
> SEACASProj_ENABLE_CONFIGURE_DEBUG:BOOL=OFF
1051c1051
< SEACASProj_ENABLE_DEBUG:BOOL=ON
---
> SEACASProj_ENABLE_DEBUG:BOOL=OFF
1543c1543
< SEACAS_ENABLE_DEBUG:BOOL=ON
---
> SEACAS_ENABLE_DEBUG:BOOL=OFF
2152c2152
< HAVE_SEACAS_DEBUG:INTERNAL=ON
---
> HAVE_SEACAS_DEBUG:INTERNAL=OFF
```
This is on a linux RHEL-7 system and a Mac.

**Comment by bartlettroscoe** [comment]
@gsjaardema, yea, this is a known problem (see #131).  This was due to a mistake I made 12 years ago in 2008 when we first stood up the Trilinos CMake build system.

Closing as duplicate.  Please comment in #131 about the urgency of fixing this.

**Comment by bartlettroscoe** [comment]
Closing as duplicate as per above.
