### ISSUE TITLE
CMake 3.20 and Policy CMP0115

### ISSUE THREAD

**Issue by jjellio** [TriBITSPub/TriBITS#364]
I had spack build the latest CMake today, and I am getting spammed by these messages at the end of Trilinos' configure.

I'm guessing this is more a Tribits thing than Tirlinos thing, so posting here.

Messages happen after (but before cmake exits)
```
Total time to configure enabled packages: 0m31.714s

Generating dummy makefiles in each directory to call Ninja ...

Total time generate Ninja makefiles Trilinos: 0m0.577s

Set up for creating a distribution ...

Total time to set up for CPack packaging: 0m0.218s

Finished configuring Trilinos!

Total time to configure Trilinos: 0m45.889s
-- Configuring done
```

```
  File:

    /tmp/coe0201/spack-stage/spack-stage-atdm-trilinos-develop-hx74jn3yrrgechhxmixka7w6md4ixdl3/spack-src/packages/tpetra/core/test/CrsMatrix/CrsMatrix_ReplaceDiagonal.cpp
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:68 (TRIBITS_ADD_EXECUTABLE)
  cmake/tribits/core/package_arch/TribitsAddExecutableAndTest.cmake:214 (TRIBITS_ADD_EXECUTABLE_WRAPPER)
  packages/tpetra/core/test/CrsMatrix/CMakeLists.txt:276 (TRIBITS_ADD_EXECUTABLE_AND_TEST)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/tribits/core/package_arch/TribitsAddExecutable.cmake:573 (ADD_EXECUTABLE):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
```

After a bit of spam, I also get these:
```
CMake Warning at cmake/tribits/core/package_arch/TribitsLibraryMacros.cmake:819 (ADD_LIBRARY):
  Cannot generate a safe runtime search path for target exodus because there
  is a cycle in the constraint graph:

    dir 0 is [/home/users/coe0201/src/spack/opt/spack/cray-rhel8-zen/cce-11.0.4/netcdf-c-4.7.4-xy6s7laodjfu3wbjurscdimlj2fs5l4g/lib]
    dir 1 is [/home/users/coe0201/src/spack/opt/spack/cray-rhel8-zen/cce-11.0.4/hdf5-1.10.7-isash4eppgf3jl7obt3ragc3amevgqh7/lib]
    dir 2 is [/home/users/coe0201/src/spack/opt/spack/cray-rhel8-zen/cce-11.0.4/libszip-2.1.1-7xxqod5bwwgk5vb4b4pspzfx44662ent/lib]
    dir 3 is [/home/groups/coegroup/atdm-dev/atdm-spack/software/view/lib]
      dir 5 must precede it due to runtime library [libz.so.1]
    dir 4 is [/home/users/coe0201/src/spack/opt/spack/cray-rhel8-zen/cce-11.0.4/parallel-netcdf-1.12.1-j3fn5xforvzzfcvl4xrbvgklle6y4sd6/lib]
    dir 5 is [/home/users/coe0201/src/spack/opt/spack/cray-rhel8-zen/cce-11.0.4/zlib-1.2.11-ng3lcngj5swchnsiwdfyemtehoyvpmht/lib]
      dir 3 must precede it due to runtime library [libz.so.1]

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  packages/seacas/libraries/exodus/CMakeLists.txt:31 (TRIBITS_ADD_LIBRARY)
```

(LOTS of these)

Adding a zip of the CMake line + configure. I only skimmed the errors, I guess there could be more classes of errors - but I know these two are common.

[cmake-20-tribits-trilinos-atdm.txt.zip](https://github.com/TriBITSPub/TriBITS/files/6281553/cmake-20-tribits-trilinos-atdm.txt.zip)

**Comment by bartlettroscoe** [comment]
@jjellio, thanks for bringing this to my attention.  The `Policy CMP0115 is not set: Source file extensions must be explicit` warning is likely a TriBITS issue.  I will take care of this once I test with CMake 3.20.  The second issue with libraries might not be a TriBITS thing but might be how the libraries are being fed into the configuration.  I will have to see if other configurations of Trilinos (using the ATDM Trilinos configuration) show this too.

**Comment by jjellio** [comment]
After looking more, the library errors are interesting. I usually use static, but there's a bug with spack so I'm using shared. It looks like spack is including a 'view' that it shouldn't.

It's neat that Cmake is reporting this circular problem (I'm guessing zlib is in both the 'view' and the spack long path. Spack isn't enforcing an ordering on shared libraries, hence cmake doesn't like the arbitrary order that spack is producing.

If I resolve that I post back

**Comment by jjellio** [comment]
I was able to resolve the library errors by using the newer ATDMDevSettings variable to skip NetCDF's `find_package` call. (it was messing up... I had given a good static link line to `ATDM_CONFIG_NETCDF_LIBS` - and it really should just use that.

It's good that settings file provides a way to dodge it.

(library link line is dumped by SPACK based on how I build HDF5 - a pretty nice feature I've added to that build process - it effectively promises to give you the right link line).

**Comment by bartlettroscoe** [comment]
> I was able to resolve the library errors by using the newer ATDMDevSettings variable to skip NetCDF's find_package call

@jjellio, what "newer ATDMDevSettings variable" is that?

**Comment by jjellio** [comment]
Maybe it's not new, but it was new to me:
https://github.com/trilinos/Trilinos/blob/57c60c8e9b57cfa0ff5645704cd88cba836eb285/cmake/std/atdm/ATDMDevEnvSettings.cmake#L25

**Comment by bartlettroscoe** [comment]
> Maybe it's not new, but it was new to me

@jjellio, FYI, that var has been there since:

```
$ git log-short --reverse -SUSE_SPARC_TPL_FIND_SETTINGS -- cmake/std/atdm/

49d7dad "Add env var ATDM_CONFIG_USE_SPARC_TPL_FIND_SETTINGS (#3632)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Tue Oct 30 12:26:47 2018 -0600 (2 years, 6 months ago)

...
```

**Comment by bartlettroscoe** [comment]
@jhux2 

These policy [`CMP0115`](https://cmake.org/cmake/help/v3.23/policy/CMP0115.html?highlight=cmp0115) warnings are not from TriBITS, they are from Trilinos CMakeLists.txt files.  The warning is that the sources are being passed in without an extension.  

For example, from the configure output at:

*  https://testing.sandia.gov/cdash/build/10672154/configure

the warning

```
CMake Warning (dev) at /data/nightlyTesting/Trilinos/cmake/tribits/core/package_arch/TribitsAddExecutable.cmake:573 (add_executable):
  Policy CMP0115 is not set: Source file extensions must be explicit.  Run
  "cmake --help-policy CMP0115" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  File:

    /data/nightlyTesting/SEMS-OPENMPI-4.0.5_RELEASE_NO-INT_OPENMP_EXPERIMENTAL/Trilinos/packages/teuchos/parameterlist/test/XMLParser/XMLParser_ParseWithoutFailing.cpp
Call Stack (most recent call first):
  packages/teuchos/parameterlist/test/XMLParser/CMakeLists.txt:30 (TRIBITS_ADD_EXECUTABLE)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

is coming from Trilinos.  If you look at that Trilinos CMakeLists.txt file in Trilinos at:

https://github.com/trilinos/Trilinos/blob/2a31ff2a3348752f416320d85ce25c4a0404e395/packages/teuchos/parameterlist/test/XMLParser/CMakeLists.txt#L30-L34

you see:

```
TRIBITS_ADD_EXECUTABLE(
  XMLParser_ParseWithoutFailing
  SOURCES XMLParser_ParseWithoutFailing
          ${TEUCHOS_STD_UNIT_TEST_MAIN}
)
```

See, the source file in `SOURCES XMLParser_ParseWithoutFailing` is missing the extension `.cpp`.

[Git blame of that file](https://github.com/trilinos/Trilinos/blame/2a31ff2a3348752f416320d85ce25c4a0404e395/packages/teuchos/parameterlist/test/XMLParser/CMakeLists.txt#L30-L34) shows this was added in Trilinos commit https://github.com/trilinos/Trilinos/commit/4b32185d10cd059e0b566ba0c374ffc8a989933a.

I will open a Trilinos GitHub Issue for this and close this TriBITS issue (because this is not anything that can be fixed in TriBITS).
