### ISSUE TITLE
Address duplicate nightly GitHub Actions jobs

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#415]
## Next Action Status

PR #416 merged to 'master' eliminates submits to CDash from forks.  Next:  Have @gsjaardema update 'master' in his fork https://github.com/gsjaardema/TriBITS (i.e. merge https://github.com/gsjaardema/TriBITS/pull/1) ...

## Description

Somehow there are duplicate nightly builds being submitted by GitHub Actions for the `.github/workflows/tribits_testing.yml` file.  One set of builds comes from that file on the 'master' branch and the other seems to be coming from an older version of that file before the commit a45727a9434e4de52b42ecf751c037de1bdecaee that upgraded from CMake 3.21.0 to 3.21.2.  You can see evidence of this each day at ???, for example, today 2020-09-09 showing:

![image](https://user-images.githubusercontent.com/1959736/132711164-824132a2-b9bd-4f5a-9ee4-5bb8ba822a30.png)

Notice the separate builds `tribits_cmake-3.21.0_makefiles_python-3.8_g++-9` and `tribits_cmake-3.21.2_makefiles_python-3.8_g++-9`.  The build `tribits_cmake-3.21.0_makefiles_python-3.8_g++-9` does not show an "Update" column so that shows it is from a version of the file that is pretty old.

Now, the GitHub Actions in this repo shown [here](https://github.com/TriBITSPub/TriBITS/actions/workflows/tribits_testing.yml?query=event%3Aschedule) only shows the jobs running once a day showing:

![image](https://user-images.githubusercontent.com/1959736/132711868-fa61512f-f20b-40d6-a5a0-cfac339b2f4c.png)

which shows it running only once a day.

We need to remove this phantom extra nightly build because it is messing up the nightly build results on CDash.

**Comment by bartlettroscoe** [comment]
One clue we can see is that the TriBITS configure captures the git SHA1 as you can see [here](https://testing.sandia.gov/cdash/build/9890817/configure) for example for the build `tribits_cmake-3.21.0_makefiles_python-3.8_g++-9` last night showing:

```
*** Base Git Repo: TriBITS
cab6dee [Mon Jul 26 14:34:24 2021 -0400] <rabartl@sandia.gov>
Remove cache and cleanup
```

while the build ` tribits_cmake-3.21.2_makefiles_python-3.8_g++-9` last nightly configure results [here](https://testing.sandia.gov/cdash/build/9890759/configure) showed:

```
*** Base Git Repo: TriBITS
0be70f5 [Thu Sep 2 13:11:07 2021 -0400] <rabartl@sandia.gov>
Merge pull request #413 from bartlettroscoe/299-target_add_libraries-public
```

I checked and the commit cab6dee **does** exist on the 'mater' branch.  Where else does that commit exist?

So how is this schedule job getting run for this old version of the TriBITS repo at commit cab6dee?

NOTE: There are no GitHub Actions listed in my or @marcinwrobel1986's accounts at:

* https://github.com/bartlettroscoe/TriBITS/actions
* https://github.com/marcinwrobel1986/TriBITS/actions

that shows this job getting run recently.  The last runs of that job was 2 months ago in those accounts.

@marcinwrobel1986, do you have any idea how GitHub Actions is running the `schedule` job in the file `.github/workflows/tribits_testing.yml` for some old version at commit cab6dee?  Could it be from some PR branch yet to be merged or something?  Does an open PR not need to be modifying that file? Could this be some type of bug in GitHub Actions with `schedule` jobs?

**Comment by marcinwrobel1986** [comment]
Hello @bartlettroscoe ,

The Scheduled jobs are working. Below I attached a printscreen. They are working for everyday as supposed.

![Zrzut ekranu z 2021-09-09 17-39-21](https://user-images.githubusercontent.com/47597569/132717803-d4744009-445e-4a92-89ce-12a959b6a94d.png)

**Comment by marcinwrobel1986** [comment]
Hello @bartlettroscoe 
I came up with two ideas.
Currently the line on the .yml file looks like that:
```cron: '10  04  *  *  *' # Run 10 minutes after midnight EDT (4:10 UTC)```

I would try to remove `0`, so it looks like that:
```cron: '10  4  *  *  *' # Run 10 minutes after midnight EDT (4:10 UTC)```
It has to be parsed somehow, maybe it is generating some GitHub error and the job is duplicated

If that wouldn't work, then I would consider to change the time lets say `10 5  *  *  *` in order to check if it's still duplicated

**Comment by bartlettroscoe** [comment]
@marcinwrobel1986, I just pushed commit 11e21c8fedc180626710d27a7ee943f9b9469eba to 'master'.  It should cause the scheduled GHA build to run tomorrow after 6:10 AM UTC (2:10 AM EDT).  That should be well after the other mystery build tomorrow which seems to be firing off just after 4:30 AM UTC (00:30 AM EDT) as shown in [this query](https://testing.sandia.gov/cdash/index.php?project=TriBITS&begin=2021-02-01&end=2021-09-10&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Nightly&field2=buildname&compare2=61&value2=tribits_cmake-3.21.0_makefiles_python-3.8_g%2B%2B-9) in the table shown below.

<details>

<summary><b>tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 history up to 2021-09-10</b></summary>

<br>

<html>
<body>


| Site | Build Name | Update | Conf Error| Conf Warn | Build Error | Build Warn | Test Not Run | Test Fail | Test Pass | Start Time |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | 10 hours ago
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 09, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 08, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 07, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 06, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 05, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 04, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 03, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 02, 2021 - 00:36 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Sep 01, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Aug 31, 2021 - 00:38 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | b87f92 | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 30, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | b87f92 | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 29, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | b87f92 | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 28, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | b87f92 | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 27, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | b87f92 | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 26, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | b87f92 | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 25, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | b87f92 | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 24, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 23, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 22, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 21, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 20, 2021 - 00:33 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 19, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 18, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 17, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 16, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 15, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 77dcbe | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 14, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 1ba26c | 0 | 0 | 0 | 0 | 0 | 0 | 734 | Aug 13, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 3f0318 | 0 | 0 | 0 | 0 | 0 | 0 | 732 | Aug 12, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 | 3f0318 | 0 | 0 | 0 | 0 | 0 | 0 | 732 | Aug 11, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 10, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 09, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 08, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 07, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 06, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 05, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 04, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 730 | Aug 03, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Aug 02, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Aug 01, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 31, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 30, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 29, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 28, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 27, 2021 - 00:29 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 26, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 25, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 365 | Jul 24, 2021 - 00:31 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 364 | Jul 23, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 364 | Jul 22, 2021 - 00:32 EDT
ubuntu-latest | tribits_cmake-3.21.0_makefiles_python-3.8_g++-9 |   | 0 | 0 | 0 | 0 | 0 | 0 | 364 | Jul 21, 2021 - 12:39 EDT

<br class="Apple-interchange-newline">
</body>
</html>

</details>

I will check tomorrow to see what this looks like.

**Comment by bartlettroscoe** [comment]
NOTE: If I can't find out what is triggering this mystery nightly build, I will update `tribits_ctest_driver()` to call `ctest_submit(PARTS done)` as the first submit to wipe out any existing results so that this will write over them directly after a `ctest_start()` (with no APPEND).  That would be a really nice feature actually that would fix all types of submit problems (and in fact I think should be the CTest default mode on a new start).

**Comment by marcinwrobel1986** [comment]
Ok, Ross, I hope it would help. I tried to find something else than than, but no success.

**Comment by bartlettroscoe** [comment]
Bingo, I found it.  These are coming from the fork:

* https://github.com/gsjaardema/TriBITS/actions

showing:

![image](https://user-images.githubusercontent.com/1959736/132879202-6d7cf998-dd72-48cb-a89e-ead8320484e7.png)

And if you look at tip 'master' branch of that repo [here](https://github.com/gsjaardema/TriBITS/commit/cab6deebe4e41896320f434108dc9c1aa312480a) you see the top commit  https://github.com/gsjaardema/TriBITS/commit/cab6deebe4e41896320f434108dc9c1aa312480a.

@gsjaardema, can you please disable GitHub Actions in your TriBITS GitHub fork or remove the 'master' branch?  This is triggering unwanted nightly builds of TriBITS submitting to the TriBITS CDash.

**Comment by marcinwrobel1986** [comment]
Nice one Ross! @bartlettroscoe honestly I didn't know someone else is working on TriBITS apart from us and specially cloned the the repo after we did CI changes

**Comment by bartlettroscoe** [comment]
> Nice one Ross! @bartlettroscoe honestly I didn't know someone else is working on TriBITS apart from us and specially cloned the the repo after we did CI changes

@marcinwrobel1986, SEACAS is actively developed and uses TriBITS as its native CMake build system (which allows for easy integration into Trilinos through snapshotting).

This demonstrates a weakness with the GitHub integration with CDash that I had not anticipated.  To stop this from happening, we should likely change `.github/workflows/tribits_testing.yml` (or the script it calls) so that it only submits to CDash by default when the repo matches the main TriBITS repo.  (People who want to experiment with this driver can always modify the file to point to their repo when doing experimentation.)  This will stop this from happening in the future by accident (which is what happened in this case).

**Comment by marcinwrobel1986** [comment]
Honestly I haven't look at it. Any credentials there needed for submission to Cdash? Or anyone can submit anything? If there would be some credentials needed, then I would suggest to use GitHub secrets for that. Maybe that would allowed just for running Cdash from main repository.

**Comment by bartlettroscoe** [comment]
> Honestly I haven't look at it. Any credentials there needed for submission to Cdash? Or anyone can submit anything? If there would be some credentials needed, then I would suggest to use GitHub secrets for that. Maybe that would allowed just for running Cdash from main repository.

@marcinwrobel1986, it is possible to lock down CDash to require some authentication but this makes things more complex and disallows people from posting experimental results that helps to debug problems with the project.  With CDash, you can use an block-list in case someone is spamming the CDash site and you can't make them stop, you can block them.

We really just want to stop accidental submissions.  I think we can add some simple logic based on the env var [`GITHUB_REPOSITORY`](https://docs.github.com/en/actions/reference/environment-variables) (which GitHub Actions sets for you) to set CTEST_DO_SUBMIT=OFF when `GITHUB_REPOSITORY != TriBITSPub/TriBITS`.  I think adding something as simple as:

```
if: ${{ env.GITHUB_REPOSITORY == 'TriBITSPub/TriBITS' }}
```

may do the trick.

See https://docs.github.com/en/actions/reference/environment-variables.

I will give that a try and see how that goes.

**Comment by marcinwrobel1986** [comment]
Yes, that should work and do the job for TriBITS.

**Comment by bartlettroscoe** [comment]
CC: @marcinwrobel1986

I believe this is fixed with the merge of PR #416.  This ran the PR testig and merge-to-master and both submitted to CDash.  But when I pushed this same 'master' to my fork repo and ran the GitHub actions at:

* https://github.com/bartlettroscoe/TriBITS/actions

these are not triggering submits to CDash , for example, as shown [here](https://github.com/bartlettroscoe/TriBITS/runs/3569914883?check_suite_focus=true) showing:

```
...

NOTE: Setting CTEST_DO_SUBMIT=OFF since GITHUB_REPOSITORY='bartlettroscoe/TriBITS' != 'TriBITSPub/TriBITS'!
CTEST_DO_SUBMIT = 'OFF'

...

-- ENV_CTEST_DO_SUBMIT='OFF'
-- CTEST_DO_SUBMIT='OFF'

...
```

Now we just need @gsjaardema to update the 'master' branch in his fork:

* https://github.com/gsjaardema/TriBITS

and it will not matter if he has GitHub Actions enabled or not.

**Comment by bartlettroscoe** [comment]
Hello @gsjaardema,

Can you please update the ‘master’ branch in your fork:

* https://github.com/gsjaardema/TriBITS

with the ‘master’ branch in:

* https://github.com/TriBITSPub/TriBITS

?

That should eliminate the submits to CDash and you can keep the ‘master’ branch in any state you want (derived from that version) and not have to disable GitHub Actions.

Thanks!

**Comment by bartlettroscoe** [comment]
FYI: I created https://github.com/gsjaardema/TriBITS/pull/1 to make updating 'master' in the repo https://github.com/gsjaardema/TriBITS/pull a single button click.

**Comment by bartlettroscoe** [comment]
NOTE: With the merge of https://github.com/gsjaardema/TriBITS/pull/1, the extra set of nightly builds have disappeared as shown [here](https://testing.sandia.gov/cdash/index.php?project=TriBITS&date=2021-09-14&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly) showing:

![image](https://user-images.githubusercontent.com/1959736/133347344-a54ad639-7ddd-453d-ada7-c2e1d3d551f1.png)

Actions was also disabled in the repo https://github.com/gsjaardema/TriBITS.

But note that actions have **not** be turned off yet in my repo:

* https://github.com/bartlettroscoe/TriBITS/actions
and it shows that a nightly build did occur this morning at:

* https://github.com/bartlettroscoe/TriBITS/actions/runs/1232509863

but, again, it did not submit results to CDash.

Therefore, this is done done.

We can now close this as complete.
