### ISSUE TITLE
Extend support for <Package>_CXX_FLAGS to subpackages

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#442]
Currently, as described in:

* https://tribits.org/doc/TribitsBuildReference.html#adding-arbitrary-compiler-flags-but-keeping-default-build-type-flags

one can set:

```
-D <TRIBITS_PACKAGE>_<LANG>_FLAGS="<EXTRA_COMPILER_OPTIONS>"
```

to append compiler flags at the package level.  But there is currently no support for compiler options targeting the subpackage level.  This was requested in https://github.com/trilinos/Trilinos/issues/10111 for setting `ShyLU_DDFROSch_CXX_FLAGS` for the `ShyLU_DDFROSch` subpackages in the `ShyLU_DD` package.

## Possible implementations

This could be implemented in one of two options.

**Option-1:** One approach would be for `<SubPackage>_<LANG>_FLAGS` to replace `<ParentPackage>_<LANG>_FLAGS` flags such that setting:

```
  -D ShyLU_DD_<LANG>_FLAGS="<flags-1>" \
  -D ShyLU_DDFROSch_<LANG>_FLAGS="<flags-2>" \
```

would result in the flags `<flags-2>` only being appended to the `CMAKE_CXX_FLAGS` and for `<flags-1>` to be ignored for the `ShyLU_DDFROSch` subpackage while  `<flags-1>` would be appended for the other subpackages in the parent package `ShyLU_DD`.

**option-2:** The other approach would be for the `<SubPackage>_<LANG>_FLAGS` to append those in `<ParentPackage>_<LANG>_FLAGS` so that:

```
  -D ShyLU_DD_<LANG>_FLAGS="<flags-1>" \
  -D ShyLU_DDFROSch_<LANG>_FLAGS="<flags-2>" \
```

resulted in the flags `<flags-1> <flags-2>` being appended to the subpackage `ShyLU_DDFROSch` `CMAKE_CXX_FLAGS` while `<flags-1>` while  `<flags-1>` would be appended for the other subpackages in the parent package `ShyLU_DD`.

**Comment by bartlettroscoe** [comment]
@searhein, should we go with **option-1** or **option-2** [above](https://github.com/TriBITSPub/TriBITS/issues/442#issue-1117618313)?  That is really the only thing that needs to be decided here before I begin.

**Comment by searhein** [comment]
@bartlettroscoe Thank you for looking into this. 

Honestly, there is no connection/dependency between `FROSch` and other sub-packages in `ShyLU_DD`. In that sense, both options would be exactly the same for me: in practice, I would just write all flags in `ShyLU_DDFROSch_<LANG>_FLAGS`.

Somehow, option 2 feels a bit more intuitive to me, but for `ShyLU_DD` it would not make much of a difference.

**Comment by bartlettroscoe** [comment]
> Somehow, option 2 feels a bit more intuitive to me, but for `ShyLU_DD` it would not make much of a difference.

@searhein, that was my opinion as well but I wanted to get an unbiased second opinion.  I will given that a try.

**Comment by bartlettroscoe** [comment]
> Honestly, there is no connection/dependency between FROSch and other sub-packages in ShyLU_DD

@searhein, then FROSch likely should have been its own top-level package.  Generally, subpackages should be aggregated into a parent package only if they are related in some obvious way.

**Comment by searhein** [comment]
@bartlettroscoe Thank you!

I agree on that. At the point when I integrated FROSch, the idea was to gather all the DD work in ShyLU_DD. However, I agree that it would also make much sense to have FROSch as a top-level package; for instance in this case, this would make things easier. Maybe, this is something to reconsider?

**Comment by bartlettroscoe** [comment]
@searhein,

>  At the point when I integrated FROSch, the idea was to gather all the DD work in ShyLU_DD

Well, that is a relationship then (even if it is not a software relationship).

> Maybe, this is something to reconsider?

That is something you should discuss with Siva and the other Trilinos leads at some point.  I think there is some desire to actually reduce the number of top-level Trilinos packages.  But no decision on that should be made, in my opinion, until we complete TriBITSPub/TriBITS#367 and some related follow-ons.  Breaking Trilinos into different repos (with multiple packages per repo) might make more sense.  But it is not my place to speculate too much on this.

**Comment by searhein** [comment]
@bartlettroscoe I fully agree. Being able to specify the flags for FROSch individually would already help me a lot. Thanks!

**Comment by bartlettroscoe** [comment]
@searhein,

This is done in TriBITS 'master' as of PR #453 that I just merged.  Can you please review the updated documentation described at the top of PR #453 and make comments there?

I will next do the git gymnastics to cherry-pick and then snapshot back just this one commit to a branch off Trilinos 'develop'.  (I can't snapshot all of TriBITS to Trilinos due to #433).

**Comment by bartlettroscoe** [comment]
FYI: The Trilinos PR that brings just this PR back to the version in Trilinos 'develop' is  https://github.com/trilinos/Trilinos/pull/10219.

**Comment by bartlettroscoe** [comment]
This has been done for a long time with the merge of PRs #453 and https://github.com/trilinos/Trilinos/pull/10219.

Closing as complete.
