### ISSUE TITLE
Sphinx generated documentation not coping and pointing to example files correctly

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#465]
@marcinwrobel1986, I just noticed that the Sphinx generation code is not copying and setting up references to example files correctly.  For example, the correct link at:

* https://raw.githubusercontent.com/TriBITSPub/TriBITS/master/tribits/doc/guides/TribitsGuidesBody.rst

containing:

```
The basic structure of this file for a **package without subpackages** is
shown in:

  `TribitsExampleProject`_/``packages/simple_cxx/CMakeLists.txt``

which is:

.. include:: ../../examples/TribitsExampleProject/packages/simple_cxx/CMakeLists.txt
   :literal:
```

is translated in the copied/updated file:

```
tribits/doc/sphinx/copied_files/TribitsGuidesBody.rst
```

which contains:

```
The basic structure of this file for a **package without subpackages** is
shown in:

  `TribitsExampleProject`_/``packages/simple_cxx/CMakeLists.txt``

which is:

.. include:: ../copied_files/CMakeLists.txt
   :literal:
```

And that results in showing the wrong example CMakeLists.txt files as you can see by comparing the correct DocUtils-generated documentation at:

* https://tribits.org/doc/TribitsUsersGuide.html#packagedir-cmakelists-txt

which shows:

![image](https://user-images.githubusercontent.com/1959736/158033220-c32489c9-2730-45be-a4bc-f1fcb4058945.png)

to the incorrect Sphinx generated documentation at:

* https://tribitspub.github.io/TriBITS/users_guide/index.html#packagedir-cmakelists-txt

which show:

![image](https://user-images.githubusercontent.com/1959736/158033199-3355d114-41df-48d9-b03b-0bfa8fe8feb2.png)

I guess I should have reviewed this better at the time but it makes no sense to have a copied file:

```
../copied_files/CMakeLists.txt
```

Instead, you need to copy all of the examples so that relative paths are correct.  The logic here needs to be fixed.

The Sphinx-generated documentation needs to be correct if we are going to display it, or it will just confuse people.

**Comment by bartlettroscoe** [comment]
@marcinwrobel1986, I think should be fixed or we should take down the hyperlinks to the Sphinx-generated documentation so that users don't see this when coming from the tribits.org site.

**Comment by marcinwrobel1986** [comment]
@bartlettroscoe hello Ross, I will look at that first thing on Monday.

**Comment by marcinwrobel1986** [comment]
@bartlettroscoe I am on it. I have fixed already other problem I have found.

**Comment by marcinwrobel1986** [comment]
Looks good https://tribitspub.github.io/TriBITS/

**Comment by bartlettroscoe** [comment]
Yup, it looks correct.

**Comment by bartlettroscoe** [comment]
@marcinwrobel1986, related to file handling, why is there no version being produced?  As shown at:

* https://tribitspub.github.io/TriBITS/users_guide/index.html

it shows:

![image](https://user-images.githubusercontent.com/1959736/159946338-ad16a836-dac6-4eae-bcf0-9391ac855f9f.png)

My guess is that the documentation needs to be generated on the 'master' branch which produces the file `TribitsGitVersion.txt`  and then build that and copy the completed documentation to the deployment branch.

**Comment by marcinwrobel1986** [comment]
@bartlettroscoe there is literaly just `.. include::` directive. What is does it just puts whatever is in the file `TribitsGitVersion.txt` if the file is missing, then nothing is put there.

**Comment by bartlettroscoe** [comment]
> What is does it just puts whatever is in the file TribitsGitVersion.txt if the file is missing, then nothing is put there.

But that file gets created as part of the build process so why is it not there?

**Comment by marcinwrobel1986** [comment]
Maybe this function does not work on GitHub runner... no idea

```shell
function generate_git_version_file {

  _TRIBITS_TAG_PREFIX=`cat ../../../tribits_tag_prefix.txt`

  if [ -e ../../../.git ] ; then
    echo
    echo "Generating git version"
    echo
    echo `git describe --match="$_TRIBITS_TAG_PREFIX*"` > TribitsGitVersion.txt
  else
    echo "$_TRIBITS_TAG_PREFIX.{Unknown version}" > TribitsGitVersion.txt
  fi

}
```

**Comment by bartlettroscoe** [comment]
Note, this is being done correctly locally which produced:

![image](https://user-images.githubusercontent.com/1959736/159960792-a9fcdc69-2d27-4eed-87a8-35fe05f430e1.png)

**Comment by bartlettroscoe** [comment]
Seems to be fixed except for the version so that is progress.  let's close this.

**Comment by bartlettroscoe** [comment]
> Maybe this function does not work on GitHub runner

@marcinwrobel1986, yup, that looks to be the problem looking at:

* https://github.com/TriBITSPub/TriBITS/runs/5678069002?check_suite_focus=true#step:6:15

showing:

```
Generating git version

fatal: No names found, cannot describe anything.
```

We can deal with that later.

**Comment by bartlettroscoe** [comment]
The problem appears to be that GHA is doing a shallow copy with no tags:

* https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

The fix seems to be to run:

```
$ git fetch --prune --unshallow --tags
```

I will try that out.

**Comment by bartlettroscoe** [comment]
And PR #470 fixed git described as shown in:

* https://github.com/TriBITSPub/TriBITS/runs/5684037733?check_suite_focus=true#step:6:84

with the updated documentation at:

* https://tribitspub.github.io/TriBITS/users_guide/index.html

now showing:

![image](https://user-images.githubusercontent.com/1959736/160020239-90376dc3-eb98-4924-9861-1a223890143b.png)

Now this Issue is done done.
