### ISSUE TITLE
Fix installed <tplName>Config.cmake files to not point into build tree

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#500]
As described in https://github.com/trilinos/Trilinos/issues/10774#issuecomment-1190334078, the current TriBITS-installed `<tplName>Config.cmake` files are setting `<upstreamTplName>_DIR` to point into the build tree instead of the install tree.  This is breaking all of the SPARC Trilinos Integration builds starting SPARC testing day [2022-07-19](https://sparc-cdash.sandia.gov/index.php?project=SPARC&date=2022-07-19&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Trilinos%20Integration).

## Tasks

* [x] Add a failing test to show the problem in TriBITS
* [x] Fix code to work correctly

**Comment by bartlettroscoe** [comment]
NOTE: It would be good to fix this in a way that allows for relocatable installs.  So instead of creating separate `<tplName>Config.cmake` files for the build and install trees, I will create just one and set `<upstreamTplName>_DIR` based on the base directory path of the `<tplName>Config.cmake` file calling it.  That will allow the install tree to be moved and keep working (at least w.r.t. these files).

**Comment by glhenni** [comment]
This one bit GEMMA as well. Oddly, not on all platforms. I'm going to wait to get into any depth as to why it only bit us on the ASCICGPU platforms but not the ASCIC (non GPU) platforms to see if your fix gets rid of the problem.

**Comment by bartlettroscoe** [comment]
>  I'm going to wait to get into any depth as to why it only bit us on the ASCICGPU platforms but not the ASCIC (non GPU) platforms to see if your fix gets rid of the problem.

@glhenni, if the build directory is visible and accessible from the configure process for the downstream APP, it will work.  For SPARC, the Trilinos builds were done on one machine under /scratch/ different from where the SPARC configures were done and, therefore, none of the SPARC configurations could find them and they all broke.

I should have a fix in for this by the end of the day hopefully (after I get a TriBITS test to demonstrate the problem).

**Comment by bartlettroscoe** [comment]
FYI: The updated tests exposing the defect and the fix are in PR #501.

**Comment by bartlettroscoe** [comment]
This was confirmed in GEMMA testing as documented in https://github.com/trilinos/Trilinos/pull/10784#issuecomment-1192653538 and we see this issue fixed in the SPARC Trilinos Integration builds starting [2022-07-22](https://sparc-cdash.sandia.gov/index.php?project=SPARC&date=2022-07-22&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Trilinos%20Integration).
