### ISSUE TITLE
Add automatic spell checking to TriBITS

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#571]
## Description

I has been brought up several times that there are spelling errors in TriBITS documentation and source code.  Examples include #404 and comments in may PRs (e.g. https://github.com/TriBITSPub/TriBITS/pull/560#discussion_r1145416170).  I try to remember to turn on flyspell in Emacs when editing files but I don't always remember to do it.

## Possible Solutions

The best long-term solution would be to add support to TriBITS to run spell checking (with managed ignores) as part of local and GitHub Actions tests.  That way, problems would be caught early and PR could not be merged until the spelling errors (the more known words are added) are addressed.

**Comment by bartlettroscoe** [comment]
@KyleFromKitware, based on your comment https://github.com/TriBITSPub/TriBITS/pull/560#discussion_r1152128973, I have assigned this Issue to you.  Please put it in progress and add a comment if you start working on this and let's have a short conversation over MS Teams about this.

**Comment by bartlettroscoe** [comment]
FYI: I was able to install codespell on my SNL RHEL 8 machine with:

```
sudo pip3 install codespell
```

But it is showing more spelling errors.  I will fix those.

**Comment by KyleFromKitware** [comment]
This brings up a good point: we should make sure that CI is running the same version of codespell that you use locally. Perhaps we should use the PIP version in CI.

**Comment by bartlettroscoe** [comment]
> This brings up a good point: we should make sure that CI is running the same version of codespell that you use locally. Perhaps we should use the PIP version in CI.

That is a good idea.

I will commit and push my changes to this branch to make codespell pass on this TriBITS repo branch in the meantime.  Then we can merge and deploy this PR :-)

**Comment by bartlettroscoe** [comment]
> This brings up a good point: we should make sure that CI is running the same version of codespell that you use locally. Perhaps we should use the PIP version in CI.

As shown [here]() it looks like GHA is currently installing codespell version 2.1.0-1 while pip installed version 2.2.1 on my machine (and the newer version caught more possible misspelled words that I had to account for in https://github.com/TriBITSPub/TriBITS/pull/573/commits/a9fe9b7d588883ee449277d58abfe480f29818b7)

**Comment by bartlettroscoe** [comment]
Let's just call this done.  Having different versions of codespell has not been a big problem.
