### ISSUE TITLE
Allow NetCDF without HDF5

### ISSUE THREAD

**Issue by ibaned** [TriBITSPub/TriBITS#574]
It is possible to compile NetCDF without HDF5 and even to build SEACASExodus with this and just use the "netcdf3" instead of "netcdf4" format to write Exodus files. However, TriBITS assumes that NetCDF requires HDF5 and unlike the package dependency system I do not see a clear way to change that dependency to being optional (could just be my lack of knowledge of TriBITS). Is there a way to make NetCDF only optionally dependent on HDF5 in TriBITS' common TPLs?

Thanks!

**Comment by bartlettroscoe** [comment]
> However, TriBITS assumes that NetCDF requires HDF5 and unlike the package dependency system I do not see a clear way to change that dependency to being optional (could just be my lack of knowledge of TriBITS).

@ibaned, that was a defect that was later fixed.  See:

* https://github.com/TriBITSPub/TriBITS/blob/master/tribits/CHANGELOG.md#2023-01-06

You can configure Trilinos with NetCDF on but HDF5 off.

Let me know if you see something different and please provide reproducibility info.

**Comment by bartlettroscoe** [comment]
And you can see this made it into Trilinos 14.0 in:

* https://github.com/trilinos/Trilinos/blob/trilinos-release-14-0-branch/cmake/tribits/CHANGELOG.md#2023-01-06

**Comment by gsjaardema** [comment]
It is possible to build netCDF without HDF5, but it provides lessened functionality.  I guess I have no problems with this PR, but I hope that it doesn't become the normal way of building.

**Comment by ibaned** [comment]
Thanks for the quick responses everyone! I'll change direction and try to get the rest of my build working with HDF5 enabled.

**Comment by gsjaardema** [comment]
> Thanks for the quick responses everyone! I'll change direction and try to get the rest of my build working with HDF5 enabled.

It is a good option to have since avoiding HDF5 in a build can really speed it up.  Most of my builds also use CGNS which requires HDF5, so I don't usually build the non-HDF5-enabled netCDF, but I should probably add a CI build that does this just to make sure that there is nothing relying on having HDF5.

**Comment by bartlettroscoe** [comment]
@ibaned, could you please post a PR to this TriBITS repo matching the same PR you posted to the SEACAS repo:

* https://github.com/sandialabs/seacas/pull/374

Then when TriBITS gets updated in Trilinos and other TriBITS projects, they will get the same versions of these files.
