### ISSUE TITLE
TriBITS Python scripts do not work on some modern Linux distributions

### ISSUE THREAD

**Issue by sebrowne** [TriBITSPub/TriBITS#607]
As per https://peps.python.org/pep-0394, `python` may not exist on some modern Linux operating systems.  The particular one in question here is RHEL8.  If you install one of the python3 packages, you do get `python3`, but not `python`.  As per the PEP, I think it wise to discontinue use of `python`, given the end-of-life of Python 2.

This specifically applies to the use of the `#!/usr/bin/env python` idiom present in many of the TriBITS Python scripts.  This is causing issues for the Trilinos AutoTester on RHEL8.

**Comment by bartlettroscoe** [comment]
Yup, TriBITS Python code was updated to Python3 years ago, and enough years have gone by that Python3 is universally available (especially with the switch to RHEL8 at SNL).   (NOTE: Python 2.7 was the default Python for RHEL7, see [here](https://access.redhat.com/discussions/4819071#:~:text=With%20RHEL%207%20%2C%20we%20have,as%20well%20as%20Python%203%20.)!)
