### ISSUE TITLE
TriBiTS must have version 3.23.0 or higher

### ISSUE THREAD

**Issue by zhengqigao** [TriBITSPub/TriBITS#612]
When I do `./do-configure`, I get the following error:

```
Make Error at tribits/core/common/TribitsConstants.cmake:17 (message):
  Error, TriBiTS must have version 3.23.0 or higher!
Call Stack (most recent call first):
  tribits/core/package_arch/TribitsProjectImpl.cmake:33 (tribits_asesrt_minimum_cmake_version)
  tribits/core/package_arch/TribitsProject.cmake:40 (include)
  tribits/TriBITS.cmake:27 (include)
  CMakeLists.txt:14 (include)
```

What might be the problem?

**Comment by zhengqigao** [comment]
3.18.0

**Comment by zhengqigao** [comment]
Actually, I am installing Trilinos using Cmake. I manually change the CmakeList.txt in Trilinos to allow Cmake 3.18.0 and then compile Trilinos. But then it shows error:

```
cmake -DCMAKE_INSTALL_PREFIX=./build ./Trilinos
CMake Error at cmake/tribits/core/common/TribitsConstants.cmake:17 (message):
  Error, TriBiTS must have version 3.23.0 or higher!
Call Stack (most recent call first):
  cmake/tribits/core/package_arch/TribitsProjectImpl.cmake:33 (tribits_asesrt_minimum_cmake_version)
  cmake/tribits/core/package_arch/TribitsProject.cmake:40 (include)
  cmake/tribits/TriBITS.cmake:27 (include)
  CMakeLists.txt:30 (INCLUDE)
```

I guess I need to install TriBiTS first, but I failed with the error provided at the beginning of this post.

**Comment by bartlettroscoe** [comment]
> 3.18.0

@zhengqigao, a CMake version 3.23.0 or higher is needed to build TriBITS or any project that uses TriBITS.  It appears we may need to improve that error message some to make this more clear.  I will put in a PR that does that.

**Comment by bartlettroscoe** [comment]
@zhengqigao, here is the PR that should make this error message more clear:

* #613

Thanks for raising this issue!

**Comment by bartlettroscoe** [comment]
> Actually, I am installing Trilinos using Cmake. I manually change the CmakeList.txt in Trilinos to allow Cmake 3.18.0 and then compile Trilinos. But then it shows error:

@zhengqigao, you don't need to bother with TriBITS directly.  Trilinos has its own snapshotted copy of TriBITS that is compatible with that version of Trilinos (see [TriBITS directory snapshotting](https://tribitspub.github.io/TriBITS/maintainers_guide/index.html#tribits-directory-snapshotting)).  (What version of Trilinos are you trying to build?)

**Comment by bartlettroscoe** [comment]
@zhengqigao, after upgrading to CMake 3.23+, can you now install Trilinos?  (NOTE: The improved error message in #613 should hopefully make this more clear for others.)

Can we close this issue?

**Comment by bartlettroscoe** [comment]
No response in last month to question from user to confirm.  Assuming this is resolved.
