### ISSUE TITLE
Using find_package(Package) during configure requires missing <Package>Targets.cmake file

### ISSUE THREAD

**Issue by rhoope** [TriBITSPub/TriBITS#623]
I'm attempting to upgrade Dakota's Trilinos version to the latest, 16.1, and am hitting a configure-time error related to changes in how <Package>Config.cmake files are being handled.

Previously, a TeuchosConfig.cmake file would get created during the Trilinos configure step called by Dakota via add_subdirectory($TRILINOS_SRC), and that file would then get used downstream via find_package(Teuchos) by Dakota and a few other of its TPLs.  Now however, TeuchosConfig.cmake gets created as before but contains a line to include a TeuchosTargets.cmake file that doesn't get created until after doing  make install. Dakota and its TPLs can no longer use find_package(Teuchos) at configure time, and I wanted to see if there might be an option in TriBITs that could force the TeuchosTargets.cmake file to get created sooner or some other way to handle this?

**Comment by bartlettroscoe** [comment]
@rhoope, you should be using the config files in the build tree. See:

* https://docs.trilinos.org/files/TrilinosBuildReference.html#using-packages-from-the-build-tree-in-downstream-cmake-projects

Otherwise, can you give some more details about what you are attempting and what is happening?

**Comment by bartlettroscoe** [comment]
> Now however, TeuchosConfig.cmake gets created as before but contains a line to include a TeuchosTargets.cmake file that doesn't get created until after doing make install. 

@rhoope, the issue might be the TeuchosTargets.cmake file in the build tree does not get created until generation time.  See:

https://github.com/TriBITSPub/TriBITS/blob/ade2bbbb57767f38b1e6efd464d50753717403fa/tribits/core/package_arch/TribitsInternalPackageWriteConfigFile.cmake#L99

So you can't just do:

```
add_directory(teuchos)
```

and then expect to call:

```
find_package(Teuchos)
```

in the same CMake project.

But if you are going to pull in Teuchos with `add_directory(teuchos)` then there is no need to call `find_package(Teuchos)`.  You already have everything you need to use Teuchos.  Once you do `add_subdiretory(teuchos)` then the modern `Teuchos::all_libs` target is already defined and ready to use.   See:

* https://tribitspub.github.io/TriBITS/users_guide/index.html#tribits-compliant-package
* https://tribitspub.github.io/TriBITS/users_guide/index.html#tribits-compliant-internal-packages

So you can just do:

```
target_link_libraries( <your-target>
  PRIVATE Teuchos::all_libs)
```

Please let me know if you have questions about this or want me to look at your CMakeLists.txt file.

**Comment by rhoope** [comment]
@bartlettroscoe That approach seems to work.  Thanks for the help and the pointers!

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe That approach seems to work. Thanks for the help and the pointers!

Thanks @rhoope!  Closing as complete 😊

(If something does not work correctly, we can reopen.)
