### ISSUE TITLE
Change "WARNING" output that is not actually a warning to a "NOTE" to avoid CDash configure warnings

### ISSUE THREAD

**Issue by clarnokt** [TriBITSPub/TriBITS#84]
TriBITS is currently printing several types of information prefixed with "WARNING".  These are not really warnings but just bits of extra info for the user to look at.  The problem is that newer versions of CDash are flagging lines with "WARNING" in the CMake output as warnings.  This was observed in #80 and fixed for that case.

This Story Issue is to find all of the places where TriBITS is printing "WARNING" but should be printing "NOTE" to avoid these CDash warnings and make it more clear that many of these are not things that the user should change.

One example is in the file "tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake", for example:

```
[kto@pu239 TriBITS]$ git diff
diff --git a/tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake b/tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake
index 9d191cd..96194f7 100644
--- a/tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake
+++ b/tribits/core/package_arch/TribitsProcessPackagesAndDirsLists.cmake
@@ -357,7 +357,7 @@ FUNCTION(TRIBITS_IMPLICIT_PACKAGE_ENABLE_IS_ALLOWED  UPSTREAM_PACKAGE_NAME_IN  P
     SET(IMPLICIT_PACKAGE_ENABLE_ALLOWED TRUE)
   ELSE()
     IF (UPSTREAM_PACKAGE_NAME_IN)
-      MESSAGE("-- " "WARNING: Not Setting ${PROJECT_NAME}_ENABLE_${PACKAGE_NAME_IN}=ON"
+      MESSAGE(STATUS "Not Setting ${PROJECT_NAME}_ENABLE_${PACKAGE_NAME_IN}=ON"
         " even though ${UPSTREAM_PACKAGE_NAME_IN} has an optional dependence on"
         " ${PACKAGE_NAME_IN} because ${PROJECT_NAME}_ENABLE_SECONDARY_TESTED_CODE=OFF" )
     ENDIF()
```

**Comment by bartlettroscoe** [comment]
A quick look through TriBITS Core shows 122 lines matching 'WARNING':

```
[8vt@u235 package_arch (master)]$ grep -nH WARNING * | wc -l
122
```

Some of these will be valid warnings for deprecated features (i.e. warnings that will turn into errors when the feature is removed).

I will wade through these and change all of the once that should obviously be "NOTE" to such.

**Comment by bartlettroscoe** [comment]
I am going to get this fixed pretty quickly here.  It was just raised again in #271.

**Comment by bartlettroscoe** [comment]
With the push of the commit de606e5c5adfdff290df02c2e9137539300e9999 to TriBITS GitHub 'master' and the merge of TriBITS snapshot to Trilinos in Trilinos PR https://github.com/trilinos/Trilinos/pull/4218 to Trilinos 'develop', this should now be resolved.

Closing as complete.
