### ISSUE TITLE
Move all TriBITS testing from Trilinos-based to TriBITS-based builds and post to my.cdash.org TriBITS project

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#87]
For the last few years, TriBITS has been tested under Trilinos-based builds and posted to the Trilinos CDash server at testing.sandia.gov.  When TriBITS became its own seprate git repo, I added TriBITS as a TriBITS git repo listed in Trilinos/cmake/ExtraRepositoriesList.cmake to clone from github.com.

There are a few problems with this.  First, it looks like most of the automated builds of TriBITS have been disabled and there is only a couple left.  Not much testing going on there.  Second, if the version of TriBITS snapshotted into Trilinos/cmake/tribits/ is inconsistent with the version of TriBITS on github.com/TriBITSPub/TriBITS 'master', then you get failed testings, for example, like [this one](http://testing.sandia.gov/cdash/testDetails.php?test=31334230&build=2201693) which is currently happening.  This is bad.  You have to basically snapshot TriBITS to Trilinos every time you update the 'master' branch of TriBITS on github.com.  That is just stupid.

Because Trilinos is not really doing any testing of TriBITS anyway anymore and it is compersome to update TriBITS on github.com and Trilinos at the same time, I am going to turn off the testing of TriBITS under Trilinos.  Note that TriBITS is already being tested under VERA testing pulling from the casl-dev.ornl.gov repo (which is the one that matters for CASL VERA which funds 99% of TriBITS development these days) and there is a Travis CI server testing TriBITS for one build on github.com.

What needs to happen, is that I need to set up a TriBITS-based CTest/CDash build of TriBITS and post to the new [TriBITS my.cdash.org project](http://my.cdash.org/index.php?project=TriBITS).

**Comment by bartlettroscoe** [comment]
I have updated the [TriBITS CDash Dashboard wiki page](https://github.com/TriBITSPub/TriBITS/wiki/TriBITS-CDash-Dashboard) and I have pushed the following commit to the Trilinos repo 'master' branch on software.sandia.gov:

```
addf90e "Remove TriBITS from being tested under Trilinos (TriBITS #87)"
Author: Roscoe A. Bartlett <bartlettra@ornl.gov>
Date:   Mon Sep 28 20:33:21 2015 -0400 (34 minutes ago)

M       cmake/ExtraRepositoriesList.cmake
```

I am going to leave this Story in the backlog until I find the time to set up this testing.  This testing should be set up as part of:

* [Make TriBITS itself use the ctest_driver and dashboard_driver systems and clean up and remove duplication in these systems significantly](https://docs.google.com/document/d/1WKs8rJhI3037yKGnEVMhIx9dPN7a7uFRM5isdNAhAXI/edit#bookmark=id.cgpg2wd5zm1x).

**Comment by bartlettroscoe** [comment]
I will ping Zack once I get working on this.  This will be a nice demo for other people.

----

From: Zack Galbreath [mailto:zack.galbreath@kitware.com] 
Sent: Tuesday, February 09, 2016 4:48 PM
To: Bartlett, Roscoe A.
Cc: Bill Hoffman
Subject: Re: GitHub and CDash integration?

> On Sun, Feb 7, 2016 at 6:07 PM, Bartlett, Roscoe A. <bartlettra@ornl.gov> wrote:
> Hello Zack and Bill,
 
> Do either of you know if someone has put together some type of CTest/CDash and GitHub integration?

Yes, we have.

> Has anyone been thinking about this?  I can’t find any references to this on the web.

Yeah, sorry about that.  We have a bit of a backlog for CDash documentation at the moment, but this feature is near the top.

What we've implemented is a method for CDash to automatically comment on your PR with a direct link to the error output if something goes wrong (configure error, build error, or test failure).  This doesn't exactly match what you've described, but at the very least it should be a good start.  Let me know if this sounds interesting to you and I'll help you get it setup.

**Comment by bartlettroscoe** [comment]
See the commits just pushed to 'master' 50d8cdf, d8ca6ff, and bc66575. 

This is a huge improvement for TriBITS testing.  Now you get nice compact output to Travis CI that is updated while the build and tests are running and then a link to the CDash site for more detailed results.

**Comment by bartlettroscoe** [comment]
I also updated the page:

* https://github.com/TriBITSPub/TriBITS/wiki/TriBITS-CDash-Dashboard

I am putting this in review. 

@jwillenbring, I would like too show this to you.  This is pretty slick and a nice model for possible Trilinos testing.

**Comment by jwillenbring** [comment]
@bartlettroscoe I am interested in learning about this. Are you thinking a Skype session? I don't know if you are at SC next week, if not we could set up a time. Otherwise, I have time Monday before Thanksgiving.

**Comment by bartlettroscoe** [comment]
> I am interested in learning about this

@jwillenbring, now that we know of a fool-proof way to create a good CDash URL (using "Build Stamp" from Zack), let me implement that before we meet.  That will address the remaining issues with this.   I will create a new TriBITS Issue for the few updates to this and CC you on that.  Not much more work to be done (other than better adding automated testing and examples).
