### ISSUE TITLE
TRIBITS_ADD_EXECUTABLE DEFINES have directory scope instead of function scope

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#90]
Using TRIBITS_ADD_EXECUTABLE(... DEFINES ...) applies definitions to all source files in a directory instead of to only the source files involved with the target.

Proposed solution is to add a new TRIBITS_ADD_EXECUTABLE argument named PROPERTIES.
After adding the executable, set the target properties to the PARSE_PROPERTIES.

This would allow for:
TRIBITS_ADD_EXECUTABLE(foo SOURCES foo.f PROPERTIES COMPILE_DEFINITIONS STD ...)

**Comment by lefebvre** [comment]
New solution.
Switch the ADD_DEFINITIONS use to TARGET_COMPILER_DEFINITIONS.
Moving to after the ADD_EXECUTABLE call:
  IF (PARSE_DEFINES)
    TARGET_COMPILE_DEFINITIONS(${EXE_BINARY_NAME} PUBLIC ${PARSE_DEFINES})
  ENDIF()

works as expected.

**Comment by bartlettroscoe** [comment]
Jordan,

The problem with adding generic PROPERTIES argument is that some of these properties may collide with other properties set for a target or test.  I can't find an explicit clash with the function TRIBITS_ADD_EXECUTABLE() but if someone also expects a PROPERTIES argument added to TRIBITS_ADD_TEST(), for example, this is a problem.  For example, what if someone tried to use:

```
  TRIBITS_ADD_TEST( ...
     TIMEOUT  20.0
      PROPERTIES  TIMEOUT 10.0
    )
```

Which timeout would get used?

I think the time may have come that we ask users to set additional/rare options on a TriBITS-added targets or tests by asking them to call these functions themselves as described for [TRIBITS_ADD_LIBRARY()](https://tribits.org/doc/TribitsDevelopersGuide.html#additional-library-and-source-file-properties-tribits-add-library), [TRIBITS_ADD_EXECUABLE()](https://tribits.org/doc/TribitsDevelopersGuide.html#additional-executable-and-source-file-properties-tribits-add-executable), [TRIBITS_ADD_TEST()][https://tribits.org/doc/TribitsDevelopersGuide.html#setting-additional-test-properties-tribits-add-test), and [TRIBITS_ADD_ADVANCED_TEST()](https://tribits.org/doc/TribitsDevelopersGuide.html#setting-additional-test-properties-tribits-add-advanced-test).

What do you think about this?

**Comment by bartlettroscoe** [comment]
> New solution.
> Switch the ADD_DEFINITIONS use to TARGET_COMPILER_DEFINITIONS.
> Moving to after the ADD_EXECUTABLE call:
>  IF (PARSE_DEFINES)
>    TARGET_COMPILE_DEFINITIONS(${EXE_BINARY_NAME} PUBLIC ${PARSE_DEFINES})
>  ENDIF()
>
> works as expected.

The only problem with this solution is that it breaks backward compatibility.  I can almost guarantee that there are CMakeList.txt files that depend on this behvaior.

Would you be okay with adding `TARGET_DEFINES` to call `TARGET_COMPILE_DEFINITIONS()` and then deprecating `DEFINES`?

**Comment by lefebvre** [comment]
When you say breaks backward compatibility you are talking about folks counting on the directory scope behavior now? I don't have time to add TARGET_DEFINES, but I would be fine going this route and then deprecating DEFINES.

**Comment by bartlettroscoe** [comment]
> When you say breaks backward compatibility you are talking about folks counting on the directory scope behavior now? I don't have time to add TARGET_DEFINES, but I would be fine going this route and then deprecating DEFINES.

I talked with Jordan over the phone and the plan will be for me to add`

**Comment by bartlettroscoe** [comment]
Jordan,

As see, I pushed the commit.  I will merge and push to the casl-dev/master repo next.

-Ross
