### ISSUE TITLE
Trilinos Bug 6131: check-in test script claims to write pullInitial.*.out, but never does 

### ISSUE THREAD

**Issue by mhoemmen** [TriBITSPub/TriBITS#91]
See Trilinos Bug 6131: 
https://software.sandia.gov/bugzilla/show_bug.cgi?id=6131

Karen Devine writes: 

When an initial pull fails in the checkin-test.py script, the following message appears:

Failed because initial pull failed! See 'pullInitial.*.out'

However, no file with this name exists when an error occurs due to having an untracked file in the repository.  The actual error message is somewhere near the middle of checkin-test.out.

**Comment by mhoemmen** [comment]
I am getting the same problem when a pull fails on my machine for some reason other than untracked files.  I am able to do "git pull" directly, and the repo is clean, but the check-in test script still refuses to pull.

**Comment by bartlettroscoe** [comment]
Mark,

My guess is that you are using a newer version of git and the script may not be working with that version yet.  What version of git are you using?

I am on personal travel so I may not be able to get to this till Monday morning or Monday afternoon (have to fly to TN monday).

**Comment by mhoemmen** [comment]
Thanks for the reply!  I tried both git 1.7.x and 2.1.x.  Both have the same trouble.

**Comment by mhoemmen** [comment]
I actually got the pull to work on my workstation.  This could be related to the hostname changing while that shell was running, and resulting brokenness with ssh keys.

If the pull succeeds, the check-in test script does successfully write pullInitial.success and pullInitial.out to the check-in test directory.

**Comment by bartlettroscoe** [comment]
Okay, that makes sense.  But that pullInitial.out file should have existed in the case where the the pull failed too.  Did it not?

Anyway, I need to change the error message to just tell you to look at the checking-test.log to see what command failed and what the sublog file is.

**Comment by mhoemmen** [comment]
pullInitial.out didn't exist in the case where the pull failed, alas.  Thanks Ross for working on this!

**Comment by bartlettroscoe** [comment]
I have created TriBITS #93 to address the root of the problem, i.e. a bad error message.  Therefore, I am closing this Issue and defer to #93.
