### ISSUE TITLE
checkin-test.py: Remove wrong sublog file from error message

### ISSUE THREAD

**Issue by bartlettroscoe** [TriBITSPub/TriBITS#93]
The checkin-test.py script currently tries to give a hint at what sublog file (i.e.g pullInitial*out) to look at when something fails.  The problem is that this is not very accurate in all cases (see #91 for an example).

This Story Issue will be to remove the guesses at the sublog file and just tell the user to grep the checkin-test.out log file for "failed" and then read the sublog file listed in the failed command.

@mhoemmen, that should help to avoid this type of confusion in the future.

Longer term, it would be nice of the checkin-test.py script gave the exact log file to look at accurately (which it could do using some software engineering involving the echoRunSysCmnd() function and a special exception class that has a logFile() method) but that will have to be a future todo.

**Comment by mhoemmen** [comment]
Thanks Ross!  I'm OK if the script just tells users where to look for the error message.

**Comment by bartlettroscoe** [comment]
I am about to push a commit that has checkin-test.py print out:

"To find out more about this failure, grep the 'checkin-test.out' log file for 'failed'.  In some cases, the failure will be obvious.  In other cases, a system command failed and the details about the failure will be in the output file for the command that failed."

Hopefully that will be sufficient.

**Comment by mhoemmen** [comment]
That sounds good, thanks!  If you happen to push a manual snapshot into Trilinos, could you close the corresponding Trilinos bug?  Otherwise somebody will close it once the automatic snapshot comes in.
