### ISSUE TITLE
TribitsCTestDriverCore allow for CTEST_BUILD_TARGET override

### ISSUE THREAD

**Issue by lefebvre** [TriBITSPub/TriBITS#94]
Ross,
Several packages I develop require "install" to satisfy verification testing.
I believe this should be as easy as exposing the second build directive to environment override.

```
warroom2:TriBITS jap$ git diff
diff --git a/tribits/ctest_driver/TribitsCTestDriverCore.cmake b/tribits/ctest_driver/TribitsCTestDriverCore.cmake
index 970315d..d3cfdbf 100644
--- a/tribits/ctest_driver/TribitsCTestDriverCore.cmake
+++ b/tribits/ctest_driver/TribitsCTestDriverCore.cmake
@@ -1731,7 +1731,7 @@ FUNCTION(TRIBITS_CTEST_DRIVER)
         SET(BUILD_OR_TEST_FAILED FALSE)

         # Build the ALL target, but append the results to the last build.xml
-        SET(CTEST_BUILD_TARGET)
+        SET_DEFAULT_AND_FROM_ENV(CTEST_BUILD_TARGET "")
         MESSAGE("\nBuild ALL target for '${TRIBITS_PACKAGE}' ...\n")
         CTEST_BUILD(
           BUILD "${CTEST_BINARY_DIRECTORY}"
```

**Comment by bartlettroscoe** [comment]
Jordan,

The variable CMAKE_BUILD_TARGET is actually used in two places.  Would you be okay if this was called something like TRIBITS_PACAKGE_BUILD_TARGET?  We would then define this like:

```
...

   SET_DEFAULT_AND_FROM_ENV(TRIBITS_PACAKGE_BUILD_TARGET "")
   ...
  FOREACH(TRIBITS_PACKAGE ${${PROJECT_NAME}_PACKAGES})
   ...
        SET(CMAKE_BUILD_TARGET  "${TRIBITS_PACAKGE_BUILD_TARGET}")
        MESSAGE("\nBuild ALL target for '${TRIBITS_PACKAGE}' ...\n")
        ...
    ENDFOREACH()
```
So then you would set `TRIBITS_PACAKGE_BUILD_TARGET=install`, right?

Note that we could add a similar option to the checkin-test.py script that would allow SCALE developers to use that in pre-push testing.  It would be an option like `--built-target` and it would default to empty but for SCALE, you could make the default `--build-target=install`.

**Comment by bartlettroscoe** [comment]
@lefebvre, I actually just added support for this in commit adbf3c11f154d5b308fcc7e0188588892de6c488 for a similar reason.  Sorry it took so long.
