### ISSUE TITLE
check-in test script pull fails with git 2.1.3; succeeds with git 1.7.1

### ISSUE THREAD

**Issue by mhoemmen** [TriBITSPub/TriBITS#97]
This is related to `eg` no longer receiving updates for newer versions of git.  It's unfortunate that we need to use git > 1.7.10 (RHEL 6 default is 1.7.1) to fix an ssh bug for accessing Trilinos through Github, but nevertheless cannot use git 2.x with the check-in test script.

**Comment by mhoemmen** [comment]
Use of git 2.1.3 results in "INITIAL PULL FAILED", even if manually running "git pull" works fine.  The error message says to grep the output file for "failed", but that gives no indication of the cause of this error.

**Comment by bartlettroscoe** [comment]
Yea, this is a know issue.  The plan is to get rid of 'eg' altogether and get working with multiple versions of raw git (see #15).

**Comment by bartlettroscoe** [comment]
Given that this is a blocker for usage by Trilinos, I will try to get this done this week.

**Comment by mhoemmen** [comment]
Awesome, thanks Ross!!!

On Nov 23, 2015, at 6:13 AM, Roscoe A. Bartlett <notifications@github.com<mailto:notifications@github.com>> wrote:


Given that this is a blocker for usage by Trilinos, I will try to get this done this week.

-

**Comment by bartlettroscoe** [comment]
@mhoemmen, as mentioned in #15, this should be fixed now.  Please verify on your side.

**Comment by bartlettroscoe** [comment]
Mark, as mentioned in #15, the issue with `--against` while doing a rebase should be resolved now.  Please verify on your side.

**Comment by mhoemmen** [comment]
I am now able to use the check-in test script.  I haven't tested the case where a rebase is necessary, but I think it's OK.  Thanks Ross!!! :-D

**Comment by bartlettroscoe** [comment]
@mhoemmen, since you have done several pushes now, I will assume this is okay.  Closing as complete.

**Comment by mhoemmen** [comment]
Works for me; thanks!!!
